### ISSUE TITLE
LICENSE? (CC BY 4.0 or MIT? )

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/images#101]
Is there a discrepancy between the LICENSE file and the README description?

https://github.com/devcontainers/images/blob/017b8e69f3beefa7ecf5d1af6c26341c9ef825c9/README.md?plain=1#L46-L49

https://github.com/devcontainers/images/blob/017b8e69f3beefa7ecf5d1af6c26341c9ef825c9/LICENSE#L1-L3

**Comment by samruddhikhandale** [comment]
Thanks for pointing that out. Closing as fixed! 👍
