### ISSUE TITLE
Support Node 22 scheduled for April 23rd

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1015]
Depends on https://hub.docker.com/_/node/tags?page=&page_size=&ordering=&name=22-bookworm

TS-node
- [x] Open a PR 
- [x] Create a release
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

JS-node
- [x] Open a PR 
- [x] Released image
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by samruddhikhandale** [comment]
Node 22 is available, now waiting for the [official Node image](https://hub.docker.com/_/node/tags?page=&page_size=&ordering=&name=22-bookworm) to support it! 👀

**Comment by germancasares** [comment]
Looks like it is ready now!

**Comment by samruddhikhandale** [comment]
Released [mcr.microsoft.com/devcontainers/javascript-node:22](https://github.com/devcontainers/images/tree/main/src/javascript-node) 🎉

**Comment by samruddhikhandale** [comment]
Released [mcr.microsoft.com/devcontainers/typescript-node:22](https://github.com/devcontainers/images/tree/main/src/typescript-node) 🎉

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Can you update Templates and MCR docs for TS-Node 22 as well? Thanks!

**Comment by gauravsaini04** [comment]
Have raised PR #[47456](https://github.com/microsoft/mcrdocs/pull/47456) for MCR Docs & PR #[256](https://github.com/devcontainers/templates/pull/256) for templates

MCR Docs PR got merged while templates PR in code review (tests appear to be passing now)
