### ISSUE TITLE
Wrong Java versions in Java 17 Images

### ISSUE THREAD

**Issue by myatmin** [devcontainers/images#102]
Java images with tag `17` were being installed with `Java 11` instead of `Java 17`.

**Comment by samruddhikhandale** [comment]
Thanks for pointing that out. Taking a look.

**Comment by kubanomaha** [comment]
Todo se hubiera arreglado hablando pero no quieren hacerlo

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Samruddhi Khandale ***@***.***>
Enviado: Tuesday, September 6, 2022 4:32:01 PM
Para: devcontainers/images ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [devcontainers/images] Wrong Java versions in Java 17 Images (Issue #102)


Thanks for pointing that out. Taking a look.

**Comment by samruddhikhandale** [comment]
@myatmin the issue is now fixed.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/24955913/189184699-f4ba80bc-1fce-404f-a48d-93547f9d3f56.png">
