### ISSUE TITLE
Can't update Rust in bookworm?

### ISSUE THREAD

**Issue by bjoernbusch** [devcontainers/images#1032]
I'm developing with the Rust devcontainer `mcr.microsoft.com/devcontainers/rust:1-1-bullseye` and there I have the proper latest version of Rust `1.74.1`. When I switch the devcontainer image to the bookworm variant `mcr.microsoft.com/devcontainers/rust:1-1-bookworm` I only get `1.75.0`.

How can I update Rust in bookworm? Or when is the bookworm image being updated? I tried `rustup update`, but that didn't find an update.

**Comment by bjoernbusch** [comment]
I had too many cached images and got confused about the pinned versions. I deleted all cached images and now I have 1.77.1 Rust in bookworm. Is there a way to update Rust in the container directly or is recreating the instance without cache the solution?

**Comment by samruddhikhandale** [comment]
Hi 👋 

When the `mcr.microsoft.com/devcontainers/rust` image is released, it will publish the available `latest` rust version for the respective OS distributions. (We base out of the official [rust](https://hub.docker.com/_/rust) image)

Ideally, we'd republish the image this week which should update the rust version. However, in the meantime, can you use the [rust Feature ](https://github.com/devcontainers/features/tree/main/src/rust)to update to the latest version?

**Comment by bjoernbusch** [comment]
Awesome, that's a great hint with the features!

**Comment by samruddhikhandale** [comment]
We have published a newer version of the rust image earlier this week. Feel free to reopen if needed, thanks!
