### ISSUE TITLE
Support Cpp (Ubuntu-24.04)

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1037]
Depends on https://github.com/devcontainers/images/issues/1016

- [x] Open a PR 
- [x] Create a release
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by BurningEnlightenment** [comment]
You probably mean Ubuntu-2**4**.04 and not Ubuntu-2**2**.04, right?

**Comment by samruddhikhandale** [comment]
[mcr.microsoft.com/devcontainers/cpp:noble](https://github.com/devcontainers/images/tree/main/src/cpp) is released 🎉 

@gauravsaini04 Can you update Templates and MCR docs for cpp:noble as well? Thanks!

**Comment by gauravsaini04** [comment]
Have raised PR #[47456](https://github.com/microsoft/mcrdocs/pull/47456) for MCR Docs & PR #[256](https://github.com/devcontainers/templates/pull/256) for templates

MCR Docs PR got merged while templates PR in code review (tests appear to be passing now)
