### ISSUE TITLE
Support Alpine 3.20 scheduled for May 2024

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1050]
Depends on [[add a reference link here]](https://hub.docker.com/_/alpine/tags?page=&page_size=&ordering=&name=3.20)

- [x] Open a PR 
- [x] Create a release
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by samruddhikhandale** [comment]
[mcr.microsoft.com/devcontainers/base:alpine-3.20](https://github.com/devcontainers/images/tree/main/src/base-alpine) is now released 🎉

**Comment by gauravsaini04** [comment]
Have raised corresponding work pr's for mcr docs updation, templates updation, images updation

**Comment by samruddhikhandale** [comment]
Closing as completed 🎉
