### ISSUE TITLE
[Universal] Unpin patch version for dotnet runtime & core

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1066]
Ref: https://github.com/devcontainers/images/pull/1065/files#diff-0a764bd0944b79c46597d08357a72f308324874b8e25e7d46f302ecc0bc47bafR14

**Comment by gauravsaini04** [comment]
Have raised [pr #1091](https://github.com/devcontainers/images/pull/1091) for it

**Comment by gauravsaini04** [comment]
pr was merged..
