### ISSUE TITLE
Alpine 3.16 EOL

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1082]
- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [x] Open a PR 
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by gauravsaini04** [comment]
Have raised corresponding work pr's for mcr docs updation, templates updation, images updation
