### ISSUE TITLE
Support Deno alpine

### ISSUE THREAD

**Issue by cirolosapio** [devcontainers/images#1094]
using denoland/deno:alpine as a base image to run a devcontainer run in this error:

```sh
Error relocating /usr/local/lib/libgcc_s.so.1: _dl_find_object: symbol not found
Error relocating /usr/local/lib/libgcc_s.so.1: __cpu_indicator_init: symbol not found
Error relocating /usr/local/lib/libgcc_s.so.1: __cpu_model: symbol not found
```

[reproduction](https://github.com/cirolosapio/deno-devcontainer)

**Comment by samruddhikhandale** [comment]
Hi 👋 

Looking at your repro repo, you may want to update your `lib` local Feature to support it. I am afraid we won't be able to help with it.

Feel free to refer to https://containers.dev/implementors/features/ for more details.
