### ISSUE TITLE
Add support for [mambaorg/micromamba] images 

### ISSUE THREAD

**Issue by filip-komarzyniec** [devcontainers/images#1104]
I'd like to suggest adding a [micromamba](https://hub.docker.com/r/mambaorg/micromamba) image variant for new dev containers. 

AFAIK it's the most optimised conda-like variant for small container images. What's more it has some benefits over conda cli, like: 
* possibility to install from multi-platform _conda-lock.yml_ files, 
* some additional commands like `repoquery`,
* based on my experience it's much faster

I'll be happy to provide a PR for that.

TODO:
- [ ] Open a PR 
- [ ] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by samruddhikhandale** [comment]
Hi 👋 

We appreciate your thoughts and request for a new image, however, the `devcontainers/images` repo only accepts improvements and bug fixes for the [current set of maintained images](https://github.com/devcontainers/images/blob/main/src). Hence, we don't have any plans for adding support for new images. 

However, if you are interested then feel free to look at https://github.com/devcontainers/images?tab=readme-ov-file#how-can-i-contribute and ways on how you could publish the image by yourself, thanks!
