### ISSUE TITLE
[Debian 10 (buster)] End of Life - LTS

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1115]
https://wiki.debian.org/DebianReleases#Current_Releases.2FRepositories

![Image](https://github.com/user-attachments/assets/c758df3e-368d-47e6-a7f5-541d9f9e0fc8)

## Debian image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## CPP image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Java image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Java-8 image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Javascript-node image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## PHP image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Python image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Ruby image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Rust image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

## Typescript-node image

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by gauravsaini04** [comment]
Have pushed the remaining changes in the following 3 PR's 👍 
[images](https://github.com/devcontainers/images/pull/1129)
[templates](https://github.com/devcontainers/templates/pull/272)
[MCR Docs](https://github.com/microsoft/mcrdocs/pull/47490)

**Comment by gauravsaini04** [comment]
PR's were merged to the codebases
