### ISSUE TITLE
Support Ruby 3.3.4

### ISSUE THREAD

**Issue by viktorianer** [devcontainers/images#1123]
There is an issue with the `net-pop` gem in Ruby 3.3.3, causing dependency errors during the build process. The problem has been resolved in Ruby 3.3.4, which includes necessary fixes for the `net-protocol` gem dependency. 

Updating the DevContainer images to support Ruby 3.3.4 will address these issues. 

**Steps to Reproduce:**

1. Set up a DevContainer with Ruby 3.3.3.
2. Include the `net-pop` gem in your Gemfile.
3. Run `bundle install`.

**Expected Behavior:**

- Successful installation of all gems without dependency errors.

**Actual Behavior:**

- Dependency errors due to missing `net-protocol` gem.

### Solution

Update the DevContainer images to support Ruby 3.3.4. This update will ensure compatibility and resolve existing dependency issues related to the `net-pop` gem.

References:
https://github.com/ruby/net-pop/issues/26
https://bugs.ruby-lang.org/issues/20581
https://github.com/ruby/ruby/releases/tag/v3_3_4

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting this issue. I am releasing a `dev` tag for the Ruby image, post that I'll create a prod release by end of this week.

**Comment by samruddhikhandale** [comment]
Deployed https://github.com/devcontainers/images/pull/1126/files#diff-97a3d17cd8818d53d1610a0fdecf71a6d20e719eaeaa50c898fbc8ea98d66bafR42

**Comment by viktorianer** [comment]
> In the meanwhile, you can pin to an older image version (`1.1.6`)

Thank you for the suggestion to pin to an older image version (1.1.6). Unfortunately, I cannot adopt this approach due to a requirement from Heroku.

Heroku mandates specifying the Ruby version in the `Gemfile` to ensure the correct version is installed. Consequently, my `Gemfile` specifies Ruby 3.3.4, leading to the following error during the build process when the DevContainer image has an older Ruby version:

```
 => ERROR [app dev_container_auto_added_stage_label 10/10] RUN bundle config set --global without "production"     && bundle install     && yarn install     && yarn cache clean     && chown -R vscode:vsc  0.3s
------
 > [app dev_container_auto_added_stage_label 10/10] RUN bundle config set --global without "production"     && bundle install     && yarn install     && yarn cache clean     && chown -R vscode:vscode /app /usr/local/rvm:
0.298 Your Ruby version is 3.3.3, but your Gemfile specified 3.3.4
```

This mismatch causes the build to fail, as the base image is still on Ruby 3.3.3, while the `Gemfile` requires Ruby 3.3.4. 

Could you provide guidance on how to proceed with ensuring the DevContainer image is updated to include Ruby 3.3.4? This update is essential to align with the required Ruby version specified in my `Gemfile` and to maintain compatibility with Heroku.

Thank you!
