### ISSUE TITLE
Rust image contains deprecated vscode extension

### ISSUE THREAD

**Issue by illyrius666** [devcontainers/images#1131]
As the title says the vscode extension crates that comes with the rust image is deprecated and replaced by: Dependi (fill-labs.dependi).
![image](https://github.com/user-attachments/assets/5e8aa4c3-002a-4bb5-b71c-2b33c4c64229)

**Comment by samruddhikhandale** [comment]
Thanks for letting us know! 

The extension is installed in the Rust image by the Rust Feature.

@gauravsaini04 Can you remove [serayuzgur.crates](https://github.com/devcontainers/features/blob/main/src/rust/devcontainer-feature.json#L60) extension from the Rust Feature? thanks!

**Comment by gauravsaini04** [comment]
have raised pr for it #[1045](https://github.com/devcontainers/features/pull/1045)

**Comment by illyrius666** [comment]
Also i noticed this in the features repo:
![image](https://github.com/user-attachments/assets/731c85ba-a006-41bc-baa2-1c3fbf68a197)
as you can see the deprecated crates extension is used here too.

**Comment by samruddhikhandale** [comment]
Thanks @gauravsaini04 for cleaning up the deprecated extension from the Rust Feature. We will release a new prod build of the Rust image earlier next week.

Thanks for your patience!

**Comment by illyrius666** [comment]
closing issue since it has been solved
