### ISSUE TITLE
@sato11 : Thank you for helping to make `gh` incrementally better! 🙇

### ISSUE THREAD

**Issue by rainlay001** [devcontainers/images#1153]
@sato11 : Thank you for helping to make `gh` incrementally better! 🙇

Minor suggestion on the documentation approach.

_最初由 andyfeller 在 https://github.com/cli/cli/pull/9412#pullrequestreview-2221484333 发布_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
