### ISSUE TITLE
From https://github.com/devcontainers/cli/pull/868/files#r1702255166

### ISSUE THREAD

**Issue by rainlay001** [devcontainers/images#1155]
From https://github.com/devcontainers/cli/pull/868/files#r1702255166 

I wonder if folks might forget to add the `/` suffix to denote a folder and the CLI might incorrectly work? Should we allow `/*` instead, which seems more familiar (at least to me)? However, I am definitely open to your thoughts on this 👀

_最初由 samruddhikhandale 在 https://github.com/devcontainers/spec/pull/484#discussion_r1702393604 发布_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
