### ISSUE TITLE
.NET 7 EOL and .NET 6 EOL (only "noble")

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#1156]
- [ ] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ ] Open a PR 
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by gauravsaini04** [comment]
- Prs raised:
    - Images: https://github.com/devcontainers/images/pull/1171
    - Templates: https://github.com/devcontainers/templates/pull/281
    - Mcr docs: https://github.com/microsoft/mcrdocs/pull/47504

**Comment by gauravsaini04** [comment]
PR's were merged
