### ISSUE TITLE
[Java] Add JDK 22 support

### ISSUE THREAD

**Issue by alanondra** [devcontainers/images#1159]
JDK 22 was [released in March](https://openjdk.org/projects/jdk/22/) but the image `mcr.microsoft.com/devcontainers/java` only goes up to version 21.

**Comment by samruddhikhandale** [comment]
Hi 👋

We only provide image support for LTS versions of Java. Since v22 is not LTS, we won't be publishing the image. However, we can update the Feature (https://github.com/devcontainers/features/issues/1084) to successfully install v22 if needed.
