### ISSUE TITLE
BUG: Premature documentation for Python 3:13 (should be dev-3:13)

### ISSUE THREAD

**Issue by mor10** [devcontainers/images#1243]
As per #1221 in https://github.com/devcontainers/images/blob/main/src/python/README.md:

> ### Configuration
> 
> You can directly reference [pre-built](https://containers.dev/implementors/reference/#prebuilding) versions of this image by using the `image` property in `.devcontainer/devcontainer.json` or updating the `FROM` statement in your own `Dockerfile` with one of the following:
> 
> - `mcr.microsoft.com/devcontainers/python:3`    (latest)
> (...)
> - `mcr.microsoft.com/devcontainers/python:3.13` (or `3.13-bookworm`, `3.13-bullseye` to pin to an OS version) 

These URIs terminate in 404.

The `3.13` images are not listed here: https://mcr.microsoft.com/v2/devcontainers/python/tags/list
Nor here: https://hub.docker.com/r/microsoft/devcontainers-python

The functioning images have version name `dev-3.13` https://github.com/devcontainers/images/blob/main/src/python/history/dev.md#variant-313-bullseye

To avoid people running into these errors and not finding meaningful answers, I recommend either publishing the `3.13` series of images or updating `README.md` to show:

> - `mcr.microsoft.com/devcontainers/python:dev-3.13` (or `dev-3.13-bookworm`, `dev-3.13-bullseye` to pin to an OS version)

**Comment by eljog** [comment]
Thank you for bringing up this issue. We are planning to release the support for 3.13 to `latest` tag next week.
Going forward we should make sure to merge the doc updates only after the release //cc @gauravsaini04

**Comment by cdce8p** [comment]
It seems the release yesterday (`0.4.9`) pinned an old commit from 7 months ago.
https://github.com/devcontainers/images/tree/v0.4.9

**Comment by eljog** [comment]
Yes that was a bad release.
@ddoyle2017 is preparing a new release to fix it https://github.com/devcontainers/images/pull/1250

**Comment by ddoyle2017** [comment]
Fixed this issue in release `v0.4.10`
