### ISSUE TITLE
Dolby Access

### ISSUE THREAD

**Issue by a0983627353** [devcontainers/images#1264]
從 Microsoft Store 中取得 Dolby Access? https://apps.microsoft.com/detail/9n0866fs04w8?ocid=webpdpshare

**Comment by LeeNikki69** [comment]
Yes I did

**Comment by LeeNikki69** [comment]
I got alot of it thanks mom and ur big ass mouth

**Comment by a0983627353** [comment]
***@***.***


________________________________
寄件者: LeeNikki69 ***@***.***>
寄件日期: 2024年12月15日 上午 09:53
收件者: devcontainers/images ***@***.***>
副本: a0983627353 ***@***.***>; Author ***@***.***>
主旨: Re: [devcontainers/images] Dolby Access (Issue #1264)


Yes I did

**Comment by Mathiyarasy** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
