### ISSUE TITLE
install node feature?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/images#127]
I believe some images built from this repository have node features installed even though they do not actually have node.js installed.
Are these necessary?

https://github.com/devcontainers/images/blob/4690ca1ee6b0ea5c3bef39b14e46c0c33d01824f/src/go/.devcontainer/devcontainer.json#L17-L19

**Comment by samruddhikhandale** [comment]
Hi @eitsupi, 
It's a nice observation. 😄 

If you look at the [Node Feature](https://github.com/devcontainers/features/blob/main/src/node/install.sh), then you will observe that even though the version is `none`, it helps add other utils like `nvm`, and other dependencies to compile native node modules (node-gyp).

Hence, we have added them intentionally.

**Comment by eitsupi** [comment]
Thank you for answering.

That makes sense to me, but I am wondering where the criteria are for adding or not adding this, since there are some images that do not have the node feature installed.
I believe node.js was installed on almost all images in https://github.com/microsoft/vscode-dev-containers (because it was assumed that it would be used with vscode).

**Comment by samruddhikhandale** [comment]
README files for such images specify the need for having node handy 😄  - https://github.com/search?q=repo%3Adevcontainers%2Fimages%20%23%23%23%20Installing%20Node.js&type=code

example - 

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/24955913/192399469-6a8b0c07-cb08-4140-b446-30f7de1c9802.png">

**Comment by eitsupi** [comment]
I see. Thanks!
