### ISSUE TITLE
JAVA_HOME points to sdkman jdk home instead of microsoft Java home

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/images#158]
Migrated from https://github.com/microsoft/vscode-dev-containers/issues/1646

//cc @samruddhikhandale 

----
@dashorst said

- VSCode Version: Version: 1.71.2 (Universal) Commit: 74b1f979648cc44d385a2286793c226e611f59e7
- Local OS Version: macOS Monterrey 12.6
- Local chip architecture: Apple Silicon
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Java (no qualifiers)

The devcontainer.json points to this URL:
    https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/java

The Dockerfile points to this parent container:
```
ARG VARIANT="17-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/java:0-${VARIANT}
```

Steps to Reproduce:

1. add remote container files to project
2. select java
3. select maven (no node or gradle)
4. select java 17 (bullseye)
5. no other extensions
6. start mvn in the terminal
7. get error that JAVA_HOME is invalid

```
$ mvn help:help
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.
```

JAVA_HOME points to this:
```
$ echo $JAVA_HOME
/usr/local/sdkman/candidates/java/current
```

However when I run java --version:
```
$ java --version
openjdk 17.0.4.1 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40354 (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40354 (build 17.0.4.1+1-LTS, mixed mode)
```

And look where it gets its cup of Java from:

```
$ which java
/usr/lib/jvm/msopenjdk-current/bin/java
```

This says to me that the configuration of the Java image is not correct.

Literally a week ago this worked without any problems.

---

@Danielv123 said

I had the same issue with java 11, added the following to `.devcontainer.json` to fix it.

```json
	"containerEnv": {
		"JAVA_HOME": "/usr/lib/jvm/msopenjdk-current"
	}
```

---

@nielspardon said

It seems `JAVA_HOME` is still correctly set in the following container image tags: `0.205.4-${VARIANT}`. If you change your `Dockerfile` in the following way it should work properly again:

```diff
-FROM mcr.microsoft.com/vscode/devcontainers/java:0-${VARIANT}
+FROM mcr.microsoft.com/vscode/devcontainers/java:0.205.4-${VARIANT}
```

Just adding the manual `JAVA_HOME` env variable was not enough for me since VS Code could not communicate with the Gradle server properly.

@joshspicer since you are the one who last touched `containers/java/definition-manifest.json` can you help to get this fixed or find the right person who can fix this?

---

@samruddhikhandale Given the above comment - it looks like this is a problem with the updated image since 0.205.5 is when it switched.  Can you take a look?

**Comment by nielspardon** [comment]
My original message might have been a bit imprecise. I just picked `0.205.4` because it seemed to be the previous version referenced in the `definition-manifest.json` and that did work for me. I did some further testing and `0.205.5` also works for me. After that version `0.205.6`, `0.205.7`, `0.205.8` and `0.205.9` all have various different issues for me. I did test with the `17-bulleye` variant.

**Comment by samruddhikhandale** [comment]
Looks like a bug in the `java` template/definition in [microsoft/vscode-dev-containers](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/java)

**Comment by samruddhikhandale** [comment]
Looks like a bug in the `java` template/definition in [microsoft/vscode-dev-containers](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/java).

We are currently working on changing the `Add Dev Container Configuration files` command to dynamically pull templates from https://containers.dev/templates. Once the changes are released, it should help fix this bug as the `Java` template will be built from [devcontainers/templates](https://github.com/devcontainers/templates/tree/main/src/java) repository. 

![image](https://user-images.githubusercontent.com/24955913/196819190-8b89e01f-83ff-495c-bb23-ced7828b2ab7.png)

Validated that the bug does not appear in https://github.com/devcontainers/templates/tree/main/src/java

**Comment by samruddhikhandale** [comment]
> We are currently working on changing the Add Dev Container Configuration files command to dynamically pull templates from https://containers.dev/templates. Once the changes are released, it should help fix this bug as the Java template will be built from [devcontainers/templates](https://github.com/devcontainers/templates/tree/main/src/java) repository.

ℹ️  Update - It is now available in `Dev Containers` extension: `Pre-release` version

**Comment by samruddhikhandale** [comment]
Closing as the issue is fixed with the updated contents of the Java Template ([here](https://github.com/devcontainers/templates/tree/main/src/java)) - which is available with `Add Dev Container Configuration Files` cmd. 

![image](https://user-images.githubusercontent.com/24955913/202578159-1ec30ecf-76b4-4c1f-bab5-bde47e0bbd8b.png)

**Comment by mvhatch** [comment]
I'm running into this issue. How do I get the fix?
```
{
  "name": "automation",
  "image": "mcr.microsoft.com/devcontainers/java:21",

  // Features to add to the dev container. More info: https://containers.dev/features.
  "features": {
    "ghcr.io/devcontainers/features/java:1": {
      "version": "none",
      "installMaven": "true"
    }
  }
}
```

```
$ mvn test
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.

$ echo $JAVA_HOME
/usr/local/sdkman/candidates/java/current

$ which java
/usr/lib/jvm/msopenjdk-current/bin/java
```

**Comment by fandreuz** [comment]
I'm also getting this error, tested with Gradle

**Comment by mvhatch** [comment]
@fandreuz - I could only get it to work by specifying the same java version 2x:

```
{
  "name": "automation",
  "image": "mcr.microsoft.com/devcontainers/java:21",

  // Features to add to the dev container. More info: https://containers.dev/features.
  "features": {
    "ghcr.io/devcontainers/features/java:1": {
      "version": "21",
      "installMaven": "true"
    }
  }
}
```

**Comment by fandreuz** [comment]
Interestingly enough, this also fixes the problem for me. Thanks @mvhatch !

**Comment by gabriel-stackhouse** [comment]
I'm running into this issue as well, and yes, while I could use @mvhatch's suggestion and include the version in the feature, that would mean I'd have two installs of Java in my container - definitely not in the interest of keeping these lean.

Could we get this issue re-opened since the issue is still ongoing?

**Comment by joebowbeer** [comment]
@mvhatch wrote:

> [@fandreuz](https://github.com/fandreuz) - I could only get it to work by specifying the same java version 2x:
> 
> ```
> {
>   "name": "automation",
>   "image": "mcr.microsoft.com/devcontainers/java:21",
> 
>   // Features to add to the dev container. More info: https://containers.dev/features.
>   "features": {
>     "ghcr.io/devcontainers/features/java:1": {
>       "version": "21",
>       "installMaven": "true"
>     }
>   }
> }
> ```

If you're using the `java` feature to install java, why use the java base image?

@samruddhikhandale If the _workaround_ is to have two java installations, I think this issue should remain open.
