### ISSUE TITLE
No Ubuntu images found

### ISSUE THREAD

**Issue by biancaAlexandru** [devcontainers/images#161]
Hello, I am working an app that was using **base:0-focal**, but it seems that when creating the dev-container in VS the image is no longer found.
I have checked the list of available tags from the README and used **docker inspect --type image** (docker inspect --type image mcr.microsoft.com/devcontainers/base:0.203.0-focal) for all the **focal**, **bionic** and **ubuntu20.04** versions and only **0.201.7-ubuntu20.04** was available.
Has somebody else had this issue? How can I solve it?

**Comment by jkeech** [comment]
@biancaAlexandru those tags should exist in the registry, but the `docker inspect` command only operates on local images. Can you try running `docker pull <image>` first before you inspect the images?

Example:
```bash
$ docker inspect --type image mcr.microsoft.com/devcontainers/base:0.203.0-focal
[]
Error: No such image: mcr.microsoft.com/devcontainers/base:0.203.0-focal

$ docker pull mcr.microsoft.com/devcontainers/base:0.203.0-focal
0.203.0-focal: Pulling from devcontainers/base
3b65ec22a9e9: Pull complete 
7717a5180c5a: Pull complete 
7ac35116152e: Pull complete 
865c50a8c80f: Pull complete 
4f4fb700ef54: Pull complete 
2f6467991236: Pull complete 
0de90e49ee4e: Pull complete 
Digest: sha256:e6121cf6cd7d5aeb2823b9ded401dc063ac4a26d5da0e271af7fdaf6ea3a29d1
Status: Downloaded newer image for mcr.microsoft.com/devcontainers/base:0.203.0-focal

$ docker inspect --type image mcr.microsoft.com/devcontainers/base:0.203.0-focal
[
    {
        "Id": "sha256:460794e5a264f07182981c9d091cdfff0235bfb2ec8b080c0aef878b64fd6b4e",
        "RepoTags": [
            "mcr.microsoft.com/devcontainers/base:0.203.0-focal"
        ],
...
```

**Comment by jkeech** [comment]
Closing since this seems to be working as expected. Please let us know if you continue to see issues. Thanks!
