### ISSUE TITLE
base-debian image installs ms-dotnettools.csharp vscode extension

### ISSUE THREAD

**Issue by dhhyi** [devcontainers/images#167]
The `base-debian` image references the `ms-dotnettools.csharp` extension, which is then inherited to all derived images.
Is it okay to remove this extension in `src/base-debian/.devcontainer/devcontainer.json`?

https://github.com/devcontainers/images/blob/35c84eded76ba0fb5ac6635c066022ab381e755e/src/base-debian/.devcontainer/devcontainer.json#L20-L28

It is aready properly added in [`src/dotnet/.devcontainer/devcontainer.json`](https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/devcontainer.json)

**Comment by samruddhikhandale** [comment]
Thanks for pointing it out. ✨ 

> Is it okay to remove this extension in src/base-debian/.devcontainer/devcontainer.json?

Yes, removed via https://github.com/devcontainers/images/pull/172 🚀 

Released a new version of the `base-debian` image. All the derived images need to be rebuilt with it for the change to take effect.

Closing as fixed.
