### ISSUE TITLE
No apache log available ( php  image)

### ISSUE THREAD

**Issue by lsfera** [devcontainers/images#168]
Just noticed while trying to debug mod_rewrite.
MY configuration is copied by https://github.com/devcontainers/images/blob/main/src/php/.devcontainer/devcontainer.json with the following overrides:

```
................
	"postCreateCommand": "sudo chmod a+x \"$(pwd)\" && sudo rm -rf /var/www/html && sudo ln -s \"$(pwd)\" /var/www/html && sudo sed -i '1i ServerName localhost' /etc/apache2/apache2.conf && sudo sed -i 's/LogLevel warn/LogLevel alert rewrite:trace6/' /etc/apache2/apache2.conf && sudo mv \\/etc\\/apache2\\/mods-available\\/rewrite.load \\/etc\\/apache2\\/mods-enabled\\/rewrite.load && apachectl start"

	"remoteUser": "vscode",
	"workspaceMount": "source=(localdir)/src,target=/workspace,type=bind",
	"workspaceFolder": "/workspace"
................
```
whatever the curled url - container logs just _container started_.
Any issue with my configuration?
Thanks

**Comment by bamurtaugh** [comment]
Thanks for filing. Could you expand a bit on the additions you made to `postCreateCommand`?

And do you see the expected logs if you use the config in https://github.com/devcontainers/images/blob/main/src/php/.devcontainer/devcontainer.json without modifications?

**Comment by samruddhikhandale** [comment]
Closing as stale! 

Feel free to reopen with more details or if the issue resurfaces. thanks!
