### ISSUE TITLE
`mcr.microsoft.com/devcontainers/base:ubuntu` is still focal?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/images#170]
The README says it is the latest LTS version, but it doesn't seem to be the case.

https://github.com/devcontainers/images/blob/35c84eded76ba0fb5ac6635c066022ab381e755e/src/base-ubuntu/README.md?plain=1#L24

Note that `docker.io/library/ubuntu:latest` has already switched to jammy right after jammy was released half a year ago.

**Comment by bamurtaugh** [comment]
Thanks @eitsupi!

@samruddhikhandale I see this too - should we switch to Jammy, or update the readme?

**Comment by samruddhikhandale** [comment]
Created PR - https://github.com/devcontainers/images/pull/179 which switches to `jammy`.

Thanks @eitsupi for catching this! ✨

**Comment by samruddhikhandale** [comment]
Released `dev` tags which switches `base:dev-ubuntu` to `jammy`, looks good. I will release prod tags now. 

![image](https://user-images.githubusercontent.com/24955913/198339721-9e8b4842-d7fd-4f19-b7df-6f0681783d4f.png)

// cc @Chuxel

**Comment by samruddhikhandale** [comment]
`https://github.com/devcontainers/images/pull/179` is live now which uses `jammy` 🚀
