### ISSUE TITLE
Python 3.11 image

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/images#175]
Python 3.11 was just released, so it would make sense to have an updated mcr.microsoft.com/devcontainers/python image for it!

Originally raised as https://github.com/microsoft/vscode-dev-containers/issues/1676

**Comment by Chuxel** [comment]
PR: https://github.com/devcontainers/images/issues/175

**Comment by pamelafox** [comment]
Thanks! Does it take some time to publish to the repository? It doesn't seem to find it yet:

% docker pull mcr.microsoft.com/devcontainers/python:3.11-bullseye
Error response from daemon: manifest for mcr.microsoft.com/devcontainers/python:3.11-bullseye not found: manifest unknown: manifest tagged by "3.11-bullseye" is not found

(Sorry, just an eager beaver over here trying to figure out how these things work)

**Comment by jkeech** [comment]
We typically first push the latest commit to the [dev tags](https://github.com/devcontainers/images/actions/workflows/push-dev.yml), do some extra validation to ensure everything looks good, and then create a git tag and kick off the [official publishing action](https://github.com/devcontainers/images/actions/workflows/push.yml). Aiming to push the official ones tomorrow.

**Comment by jkeech** [comment]
@pamelafox the images have been published now, so you should be able to run `docker pull mcr.microsoft.com/devcontainers/python:3.11-bullseye`.

**Comment by pamelafox** [comment]
Thank you, it works! https://github.com/pamelafox/python-3.11-playground

**Comment by pamelafox** [comment]
Should just "3.11" work yet? I see it in the tags at https://mcr.microsoft.com/v2/devcontainers/python/tags/list but then get an error when I pull it:

>>> docker pull mcr.microsoft.com/devcontainers/python:3.11
3.11: Pulling from devcontainers/python
manifest for mcr.microsoft.com/devcontainers/python:3.11 not found: manifest unknown: manifest sha256:acbabd4f95ad76e0d2a226c50554986063a00f1e3f58d5db1efc602146f16c9a is not found

**Comment by Chuxel** [comment]
> Should just "3.11" work yet? I see it in the tags at https://mcr.microsoft.com/v2/devcontainers/python/tags/list but then get an error when I pull it:

Yes. If it's not working, there may be something regional going on with MCR. If you are still hitting an issue, please raise a new issue on it since 3.11 has been out for a while now.

For me:

```
docker pull mcr.microsoft.com/devcontainers/python:3.11
3.11: Pulling from devcontainers/python
1e4aec178e08: Pull complete 
6c1024729fee: Pull complete 
c3aa11fbc85a: Pull complete 
aa54add66b3a: Pull complete 
9e3a60c2bce7: Pull complete 
3b2123ce9d0d: Pull complete 
05df7720fcb8: Pull complete 
972ab8743e38: Pull complete 
ae9f20f2cd37: Pull complete 
9bdb3ed15c1e: Pull complete 
9076bbd68847: Pull complete 
de371f904144: Pull complete 
be817188c3b1: Pull complete 
1a6b36a3432c: Pull complete 
df18b43124fc: Pull complete 
71c959405933: Pull complete 
ccfb09fd3a60: Pull complete 
Digest: sha256:dfd5864946d7ec1c598b5421e9da47c85c7585808c500707a8b11906bceb423b
Status: Downloaded newer image for mcr.microsoft.com/devcontainers/python:3.11
mcr.microsoft.com/devcontainers/python:3.11
```

**Comment by pamelafox** [comment]
Okay, it worked this morning, so perhaps an MCR issue, will keep my eye out.
