### ISSUE TITLE
Universal Image ignores USERNAME variable and enforces codespace as user

### ISSUE THREAD

**Issue by rastislav-vcrs** [devcontainers/images#189]
https://github.com/devcontainers/images/blob/de5005e033eaa4dfda48bdcf0854730c491116cf/src/universal/.devcontainer/local-features/setup-user/install.sh#L33

While reading on this script, all _user_ paths are hardcoded to `/home/codespace`. However, should that be `/home/${USERNAME}` instead to honor `USERNAME=` variable selection at the start of the file?

https://github.com/devcontainers/images/blob/de5005e033eaa4dfda48bdcf0854730c491116cf/src/universal/.devcontainer/local-features/setup-user/install.sh#L7

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the feedback. I agree that we should change it to use the `USERNAME ` variable 👍 
I would pick this up soon. 👍
