### ISSUE TITLE
[PHP] Add more extensions by default

### ISSUE THREAD

**Issue by shyim** [devcontainers/images#196]
Currently, the docker image for php contains almost no extensions. Maybe we should preinstall popular ones.

We can use also https://github.com/mlocati/docker-php-extension-installer it's better than calling pecl by own 😅

**Comment by samruddhikhandale** [comment]
Hi 👋 

Could you explain which image are you talking about when you say `docker` image?

list 👉  https://github.com/devcontainers/images/tree/main/src

**Comment by shyim** [comment]
The php one https://github.com/devcontainers/images/tree/main/src/php :)

**Comment by samruddhikhandale** [comment]
Thanks for the clarification.

This would be a good question for @craiglpeters / @Chuxel / @bamurtaugh 😄

**Comment by shyim** [comment]
I would also make a pull request if there is a guide how to test it 😄  and if that is wanted 😅

**Comment by Chuxel** [comment]
There are two types of extensions in this context. The kind you use in VS Code, and then the kind that extends PHP itself.  I assume you are talking about the latter?

**Comment by shyim** [comment]
@Chuxel yes in php itself.

**Comment by shyim** [comment]
@samruddhikhandale I made a PR :)
