### ISSUE TITLE
Update dotnet container image

### ISSUE THREAD

**Issue by timheuer** [devcontainers/images#200]
.NET 7 just released.

Update container images for .NET 7 as default

**Comment by Chuxel** [comment]
@timheuer Several PRs are queued up, but currently `universal` (aka "kitchen sink") has .NET 3 and 6.  I'm assuming this should now be 6 and 7?

**Comment by timheuer** [comment]
Should be 3.1, 6, 7

-th
________________________________

**Comment by Chuxel** [comment]
@timheuer Given 3.1 is EOL in Dec, why include it? Given the size of the image we are generally including only latest LTS for most languages by default.

**Comment by timheuer** [comment]
If the update happens after EOL that makes sense but the reality is there are two LTS right now

-th
________________________________

**Comment by Chuxel** [comment]
Yeah for the separate images we can do all three but I will have to defer to the Codespaces folks on the universal image given the desire there is to not grow it beyond its current size since that reduces usable storage.

**Comment by Chuxel** [comment]
`mcr.microsoft.com/devcontainers/dotnet:7.0` and variants are now up. The dotnet Dev Container Feature is now also updated.

@samruddhikhandale is working on the template https://github.com/devcontainers/templates/pull/39 which can get merged now that the images are released.

The `unviersal` and Codespace's use of it by default requires testing, though that is also in flight at this point w/.NET 6 and 7 being there.  (3.1, 6.0, and 7.0 are al there for the dotnet image).

**Comment by samruddhikhandale** [comment]
> @samruddhikhandale is working on the template https://github.com/devcontainers/templates/pull/39 which can get merged now that the images are released.

.NET Templates have been updated & deployed yesterday.

**Comment by samruddhikhandale** [comment]
Codespaces is now using .NET 7 as default.

Closing as features/templates/images/codespaces have been updated 🚀
