### ISSUE TITLE
Update Rust image

### ISSUE THREAD

**Issue by nasso** [devcontainers/images#209]
Rust 1.65 came out almost two weeks ago but the Rust image is still stuck on 1.64.

This is really inconvenient, as Rust cannot be upgraded by just doing `rustup update` like on a regular install.

**Comment by samruddhikhandale** [comment]
Hi @nasso  👋 

We released dev tags today which updates the rust version.

![image](https://user-images.githubusercontent.com/24955913/201782641-cf942617-8ed2-421a-ab92-6365acffae11.png)

We plan to do a prod deployment today/tomorrow. Feel free to use `mcr.microsoft.com/devcontainers/rust:dev-1` untill then. Thanks!

**Comment by nasso** [comment]
oh awesome!

**Comment by samruddhikhandale** [comment]
Rust image is deployed with v1.65.0 🚀
