### ISSUE TITLE
Images not listed on mcr.microsoft.com

### ISSUE THREAD

**Issue by pamelafox** [devcontainers/images#213]
I browsed and searched on mcr.microsoft.com to try to figure out what images are available, and I couldn't find any evidence of these images being listed there. Maybe I just browsed/searched poorly, but none of the obvious keywords worked.

I'm specifically trying to figure out what tags are available for:

mcr.microsoft.com/vscode/devcontainers/base

I did figure out how to find the tag for the languages here, like mcr.microsoft.com/devcontainers/python, by navigating through the src folder and clicking the link in the readme, but I think mcr.microsoft.com is the more obvious place to look for that info.

Thanks!

**Comment by bamurtaugh** [comment]
Thank you for opening this @pamelafox! 

We've had discussions on this over the past few months, and now that we have the /images, /features, and /templates repos and specs in place, this is a great reminder to revisit this work. We'll keep you updated with any new progress.

**Comment by bamurtaugh** [comment]
In case others discover this issue, here is the resulting link: https://mcr.microsoft.com/en-us/catalog?search=dev%20container.
