### ISSUE TITLE
Reminder issue: Ruby - Release `3.2`

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#257]
Ruby will soon publish ruby `3.2` towards end of this year. Support that!

**Comment by samruddhikhandale** [comment]
Ruby `3.2` is released. However, the docker images for `3.2` aren't released yet.

**Comment by ashkulz** [comment]
@samruddhikhandale they **are** released: see docker-library/official-images#13806

**Comment by samruddhikhandale** [comment]
Released 3.2 🎉
