### ISSUE TITLE
Add usage note to README

### ISSUE THREAD

**Issue by fulldecent** [devcontainers/images#287]
Currently the README addresses questions like customizing your own Dockerfile and adding features.

It would be nice to address, or link to, a guide explaining how to make use of the devcontainers in this repo.

For example, the other repo https://github.com/devcontainers/features currently features such helpful notes as an actual `dev container.json` file you can actually copy paste into your project to use a devcontainer and a feature.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Have you taken a look at https://containers.dev/guide/dockerfile ? 
If that's something you are looking forward to, then we could help add this ref link to all the README files.

Also, additionally we could add a similar example usage as that of Features.
eg. Feature Go https://github.com/devcontainers/features/tree/main/src/go#example-usage

For Go image's README we could have 👇 

.devcontainer.json
```jsonc
{
    "image": "mcr.microsoft.com/devcontainers/go:1"
}
```

**Comment by fulldecent** [comment]
Thank you, yes that's super helpful and I'm using it now to study how to get my Jekyll blog all devcontainerified for the future!

**Comment by samruddhikhandale** [comment]
> Have you taken a look at https://containers.dev/guide/dockerfile ?
If that's something you are looking forward to, then we could help add this ref link to all the README files.

Great, I'll put up a PR shortly for this.
