### ISSUE TITLE
building micro/patch versions

### ISSUE THREAD

**Issue by schlich** [devcontainers/images#330]
Hello,

I am wondering if there is a way to build a devcontainer using a specific micro/patch version.  Heroku deployments require specifying the patch number, at least for python, and devcontainer seems to pull the latest, which can cause the dev container to become out of sync with the repo. I'm wondering if there is a way to override this, maybe with a dockerfile ARG?  Apologies if i am missing something obvious.

**Comment by rchoulak** [comment]
merci mon dieu

**Comment by samruddhikhandale** [comment]
Hi @schlich 👋 

If you are using dev container images, then you can pin upto a minor version (eg. python 3.11 / 3.10). However, not to a patch version. 

Have you looked at [devcontainer features](https://github.com/devcontainers/features)? With it, you could install (eg. python 3.11.1) as follows 👇 

```jsonc
"features": {
    "ghcr.io/devcontainers/features/python:1": {
         "version": "3.11.1"   
     }
}
```

**Comment by schlich** [comment]
That's a great point I hadn't considered. I've use features to pin versions of other things but for some reason hadn't considered using it for the base.  Should I use that feature on top of a node devcontainer image then to get the same result? What are the upsides and downsides of installing the feature on top of, say, a node devcontainer vs a python devcontainer?  Any caching, install time, or container size considerations?

**Comment by samruddhikhandale** [comment]
> Should I use the Python feature on top of a node devcontainer image then to get the same result?

You could, if you don't have the same pinning to patch version issue. Else, you could simply use a base:ubuntu/debian image & then use Features to install node & python.

> What are the upsides and downsides of installing the feature on top of, say, a node or base linux devcontainer vs a python devcontainer?

Downsides
- If you use a python image, then the time it takes to pull an image will be a little less as compared to building from source with the python Feature. We are planning to update the Python Feature to use a prebuilt binary but haven't made progress yet - https://github.com/devcontainers/features/issues/75
- Python image uses the common-utils Feature which helps set the user, add themes, install common toolings, etc which would be missed with the Feature. However, using a base image or adding this Feature would help.

Upsides - You get more flexibility with versioning, and can make use of [Feature options](https://github.com/devcontainers/features/tree/main/src/python#options) to customize the devcontainer (eg, insta)

> Any caching, install time, or container size considerations? 

- Images & Features are both cached.
- As Python Feature currently builds from source, the time needed would be little more compared to an image
- I think size is almost the same, as both the image & Feature builds Python from source. Hence, shouldn't have a major difference.

**Comment by schlich** [comment]
an excellent and thorough response, thank you!
