### ISSUE TITLE
samruddhikhandale/release-git-reverse

### ISSUE THREAD

**Issue by gwapIgot** [devcontainers/images#337]
samruddhikhandale/release-git-reverse

_Originally posted by @gwapIgot in https://github.com/devcontainers/images/issues/335#issuecomment-1386580704_

**Comment by gwapIgot** [comment]
[](url)

**Comment by gwapIgot** [comment]
### ### ### # # #330 #334

**Comment by rchoulak** [comment]
merci mon dieu
 bravo
