### ISSUE TITLE
Java: Incorrect value is set by `JAVA_HOME` env

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#368]
```
$ printenv JAVA_HOME
/usr/local/sdkman/candidates/java/current

This is still incorrect...

$ ls -l /usr/local/sdkman/candidates/java/
ls: cannot access '/usr/local/sdkman/candidates/java/': No such file or directory

$ which java
/usr/lib/jvm/msopenjdk-current/bin/java
```

_Originally posted by @oalper in https://github.com/devcontainers/images/issues/339#issuecomment-1398740329_

**Comment by samruddhikhandale** [comment]
Opened https://github.com/devcontainers/cli/issues/381

**Comment by brimobile1** [comment]
> ```
> $ printenv JAVA_HOME
> /usr/local/sdkman/candidates/java/current
> 
> This is still incorrect...
> 
> $ ls -l /usr/local/sdkman/candidates/java/
> ls: cannot access '/usr/local/sdkman/candidates/java/': No such file or directory
> 
> $ which java
> /usr/lib/jvm/msopenjdk-current/bin/java
> ```
> 
> 
>      
>   
> 
> _Originally posted by @oalper in [#339 (comment)](https://github.com/devcontainers/images/issues/339#issuecomment-1398740329)_

**Comment by brimobile1** [comment]
> ```
> $ printenv JAVA_HOME
> /usr/local/sdkman/candidates/java/current
> 
> This is still incorrect...
> 
> $ ls -l /usr/local/sdkman/candidates/java/
> ls: cannot access '/usr/local/sdkman/candidates/java/': No such file or directory
> 
> $ which java
> /usr/lib/jvm/msopenjdk-current/bin/java
> ```
> 
> _Originally posted by @oalper in https://github.com/devcontainers/images/issues/339#issuecomment-1398740329_
>

**Comment by samruddhikhandale** [comment]
`dev` tags are updated with the fix, waiting for a prod release.

**Comment by samruddhikhandale** [comment]
Closing as fixed with the latest prod release 🚀 

![image](https://user-images.githubusercontent.com/24955913/219136861-e19542c0-b78f-4608-907e-f034d83c2f4d.png)
