### ISSUE TITLE
Rust devcontainer.json repeats customization from Rust feature

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/images#372]
It seems the customizations are just repeated and could be omitted from the devcontainer.json for simplicity. Is there a reason to have them in the devcontainer.json? (Noted in https://github.com/microsoft/vscode-remote-release/issues/7887#issuecomment-1402924648.)

**Comment by samruddhikhandale** [comment]
Good point! Looks like it was missed, I would update the `rust` image,

**Comment by samruddhikhandale** [comment]
Closing as completed!
