### ISSUE TITLE
Jekyll images do not work on Windows, because ports cannot be opened

### ISSUE THREAD

**Issue by tudortimi** [devcontainers/images#399]
I'm trying to use the Jekyll image on Windows. I'm getting the following error when trying to serve the site:

![image](https://user-images.githubusercontent.com/8170909/216463032-b865d353-4ae8-4337-88fb-25640f1340c7.png)

The port is not in use, at least not according to `lsof`:

![image](https://user-images.githubusercontent.com/8170909/216463726-233d25fd-f081-426c-8c4f-001a8d326a1a.png)

On Linux, everything works fine.

--------------------

I read that Docker has some limitations when it comes to networking. (For example, https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/). I'm not sure whether this fails due to some limitation.

**Comment by tudortimi** [comment]
I stopped forwarding the ports that the devcontainer configures and then everything started working. VS Code automatically forwards them, but uses different numbers in the host than in the container.

When the container is built, the following ports are opened:

![image](https://user-images.githubusercontent.com/8170909/216464276-9507b277-5e2c-4e71-bb2f-feea5dcd5205.png)

I stop forwarding them:

![image](https://user-images.githubusercontent.com/8170909/216464385-39ff32e0-1f7c-4c1c-b384-20cbe4742c2a.png)

I serve the site and VS Code automatically forwards the ports:

![image](https://user-images.githubusercontent.com/8170909/216464599-55c5621b-be1d-4824-8055-b24593df1e90.png)

Everything works in a browser on the host. VS Code opens the site at `http://127.0.0.1:4001/`.

---------------------

Are the explicit settings for port forwarding needed if VS Code is able to forward ports automatically? Could they be dropped from the devcontainer? If you still have to keep them for some other case, is there something I could add to the devcontainer in my repo to stop fowarding the ports and let VS Code forward them automatically?

**Comment by tudortimi** [comment]
Forgot to mention my environment:

VS Code 1.74.3
Windows 11 Home, 10.0.22621
Docker 4.16.3

**Comment by samruddhikhandale** [comment]
Hi 👋 

I tried reproducing on a Windows 11 and MacOS machine with the jekyll Template. In both cases, the site created with `jekyll serve` worked fine for me without any errors.

Looking at your screenshots, the dev config opens up ports `localhost:*` and VS auto forwards for `127.0.0.1:*`. By default, `localhost` corresponds to `127.0.0.1`. However, I wonder if you have a configuration host file which might override this behavior?

**Comment by tudortimi** [comment]
I did some more experimenting. I tried to start a simple Ruby web server in the devcontainer with the following command:

    ruby -run -ehttpd . -p8000

This works:

![image](https://user-images.githubusercontent.com/8170909/216767895-5005338c-74a4-482c-8015-e9ed6e867f5f.png)

and is autoforwarded to port 8001:

![image](https://user-images.githubusercontent.com/8170909/216767960-715d7a18-ab1c-4ad3-b2f2-72639b941e27.png)

If I try to start the server on 4000, I don't get the error message that the port cannot be opened:

![image](https://user-images.githubusercontent.com/8170909/216768018-e0815692-0509-4a87-ac0b-8df99e783d9d.png)

but afterVS Code prompts me to open the page, it hangs forever:

![image](https://user-images.githubusercontent.com/8170909/216768067-df744870-24a8-4f18-a9e0-d320bc129c5c.png)

**Comment by tudortimi** [comment]
This is what I have in my hosts file:

```
# Added by Docker Desktop
192.168.178.21 host.docker.internal
192.168.178.21 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by tudortimi** [comment]
Also, I had a look at the ports the Windows host sees and it shows VS Code listening on port 4000. I'm not sure whether this is relevant to the issue. I'm guessing `127.0.0.1` on the devcontainer isn't the same as `127.0.0.1` on the host, but I'm not sure whether Docker messes them up somehow.

**Comment by samruddhikhandale** [comment]
> 127.0.0.1       localhost

Can you add this line to the hosts config file and retry?

**Comment by tudortimi** [comment]
I tried with the entry and it still doesn't work. In any case, I read up a bit more and it seems that Docker on Windows is kind of flaky. I read many comments related to Docker updates causing this issue or suggestions that this might be related to Hyper-V. If you have a setup where it works, I'm guessing this boils down to a problem with my setup. Thanks a lot for trying to help out!

**Comment by tudortimi** [comment]
Any chance you know how I could programmatically stop the forwarding from the `devcontainer.json`, though?

**Comment by samruddhikhandale** [comment]
> Any chance you know how I could programmatically stop the forwarding from the `devcontainer.json`, though?

Unfortunately, I don't think we currently have a way to stop that. Probably nice to create a similar issue like https://github.com/devcontainers/features/issues/386 in the Features repo?
