### ISSUE TITLE
Can't pull vscode/devcontainer/python:3

### ISSUE THREAD

**Issue by rvanlaar** [devcontainers/images#409]
Can't pull docker containers, errors out with: **failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /etc/ImageMagick-6: invalid argument**

```
$ docker pull mcr.microsoft.com/vscode/devcontainers/python:3
3: Pulling from vscode/devcontainers/python
bbeef03cda1f: Pull complete 
f049f75f014e: Pull complete 
56261d0e6b05: Pull complete 
9bd150679dbd: Pull complete 
5b282ee9da04: Pull complete 
03f027d5e312: Pull complete 
591b0f932310: Pull complete 
1047c5f4cc7d: Pull complete 
5b5cbe74bf76: Pull complete 
c51641a6b361: Extracting [==================================================>]  14.13MB/14.13MB
870775825d66: Download complete 
0ea748869223: Download complete 
f3a2e6adcb8a: Download complete 
537e4ca759a0: Download complete 
6a21208cb918: Download complete 
cd75abeea0a0: Download complete 
6a6b68d36170: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /etc/ImageMagick-6: invalid argument
```

system info:
```
$ docker --version
Docker version 23.0.0, build e92dd87
$ uname -a
Linux kiesopmaat 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
```

**Comment by rvanlaar** [comment]
It seems this happens when running docker inside a container and not when running docker on a VM.

**Comment by samruddhikhandale** [comment]
Hi 👋 

I tried to reproduce this from within a container, however, docker pull was successful for me.

I used this dev config for creating the dev container👇 

```jsonc
{
	"image": "mcr.microsoft.com/devcontainers/base:ubuntu",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {}
	}
}
```

@rvanlaar I wonder if the issue is with the underlying OS for your container?

**Comment by rvanlaar** [comment]
After your comment I did check again.
Created two debian 11.6 containers. One 'unprivileged'.
This error is reproducible on the 'unprivileged' container.

**Comment by samruddhikhandale** [comment]
> This error is reproducible on the 'unprivileged' container.

I see, @rvanlaar could you help me out with repro steps? thanks!

**Comment by muss-web** [comment]
> Can't pull docker containers, errors out with: **failed to register layer: ApplyLayer exit status 1 stdout: stderr: unlinkat /etc/ImageMagick-6: invalid argument**
> 
> ```
> $ docker pull mcr.microsoft.com/vscode/devcontainers/python:3
> 3: Pulling from vscode/devcontainers/python
> bbeef03cda1f: Pull complete 
> f049f75f014e: Pull complete 
> 56261d0e6b05: Pull complete 
> 9bd150679dbd: Pull complete 
> 5b282ee9da04: Pull complete 
> 03f027d5e312: Pull complete 
> 591b0f932310: Pull complete 
> 1047c5f4cc7d: Pull complete 
> 5b5cbe74bf76: Pull complete 
> c51641a6b361: Extracting [==================================================>]  14.13MB/14.13MB
> 870775825d66: Download complete 
> 0ea748869223: Download complete 
> f3a2e6adcb8a: Download complete 
> 537e4ca759a0: Download complete 
> 6a21208cb918: Download complete 
> cd75abeea0a0: Download complete 
> 6a6b68d36170: Download complete 
> failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /etc/ImageMagick-6: invalid argument
> ```
> 
> system info:
> 
> ```
> $ docker --version
> Docker version 23.0.0, build e92dd87
> $ uname -a
> Linux kiesopmaat 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
> ```

**Comment by rvanlaar** [comment]
> > This error is reproducible on the 'unprivileged' container.
> 
> I see, @rvanlaar could you help me out with repro steps? thanks!

I use proxmox https://www.proxmox.com/en/ on the host and use their functionality to create containers:
https://pve.proxmox.com/wiki/Linux_Container

Used debian 11.6 and Inside the container I installed Docker.

**Comment by samruddhikhandale** [comment]
Thanks, @rvanlaar  can you open an issue for `proxmox` ? Looks like the issue is on their end as these images can be pulled with dev containers, locally with docker desktop and also with Codespaces.

**Comment by rvanlaar** [comment]
Thanks for your time looking into the issue.

**Comment by muss-web** [comment]
> Can't pull docker containers, errors out with: **failed to register layer: ApplyLayer exit status 1 stdout: stderr: unlinkat /etc/ImageMagick-6: invalid argument**
> 
> ```
> $ docker pull mcr.microsoft.com/vscode/devcontainers/python:3
> 3: Pulling from vscode/devcontainers/python
> bbeef03cda1f: Pull complete 
> f049f75f014e: Pull complete 
> 56261d0e6b05: Pull complete 
> 9bd150679dbd: Pull complete 
> 5b282ee9da04: Pull complete 
> 03f027d5e312: Pull complete 
> 591b0f932310: Pull complete 
> 1047c5f4cc7d: Pull complete 
> 5b5cbe74bf76: Pull complete 
> c51641a6b361: Extracting [==================================================>]  14.13MB/14.13MB
> 870775825d66: Download complete 
> 0ea748869223: Download complete 
> f3a2e6adcb8a: Download complete 
> 537e4ca759a0: Download complete 
> 6a21208cb918: Download complete 
> cd75abeea0a0: Download complete 
> 6a6b68d36170: Download complete 
> failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /etc/ImageMagick-6: invalid argument
> ```
> 
> system info:
> 
> ```
> $ docker --version
> Docker version 23.0.0, build e92dd87
> $ uname -a
> Linux kiesopmaat 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
> ```
