### ISSUE TITLE
Can't pull images from a private registry

### ISSUE THREAD

**Issue by floresjma** [devcontainers/images#415]
It used to work with 0-3.10-bullseye but started to get this message since [this build](
https://github.com/devcontainers/images/actions/runs/4001526389/jobs/6867841775) failed. Not sure if that's related.
```
docker pull my-private-registry/devcontainers/python:0-3.10-bullseye
WARNING: ⚠️ Failed to pull manifest by the resolved digest. This registry does not
	appear to conform to the distribution registry specification; falling back to
	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
	release.  Please contact admins of https://my-private-registry ⚠️

0-3.10-bullseye: Pulling from devcontainers/python
manifest verification failed for digest sha256:276b3e6ab551c21e2ba3240ed595a8940194f17cda9742f0e01753f6b65be0f5
```

However, if changing the tag to `0.204.4-3.10-bullseye`, it works. Looks like [that tag was created](https://github.com/devcontainers/images/blob/main/src/python/history/0.204.4.md#variant-310-bullseye) before the build above? 
I get above error with tag `0.204.5-3.10-bullseye`.

I am seeing this issue with `typescript-node` images and `java` as well. e.g it works for `javascript-node:0.204.14-18-bullseye` but not for `javascript-node:0-16`

Docker Info

```
~ ❯ docker --version
Docker version 20.10.22, build 3a2c30b
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

> It used to work with 0-3.10-bullseye but started to get this message since [this build](https://github.com/devcontainers/images/actions/runs/4001526389/jobs/6867841775) failed. Not sure if that's related.

The build you've linked is a test run failure for `jekyll` image and, you are trying to pull some python image hence, should not be related.

Looks like things were working for you before releasing [these image tags](https://github.com/devcontainers/images/commit/56f10e7566cf665722e314ab83d0d3bb05eec56d#diff-07b9c3f1dba1903e32787563e5c6163f85c1597891c4221cc18edd418448328d).

@floresjma Have you tried pulling the `mcr.microsoft.com/devcontainers/python:0-3.10-bullseye` image directly instead of using `my-private-registry/devcontainers/python:0-3.10-bullseye` from a private registry? 

`docker pull mcr.microsoft.com/devcontainers/python:0-3.10-bullseye` works perfectly for me.

**Comment by floresjma** [comment]
Yes, not issues with pulling `docker pull mcr.microsoft.com/devcontainers/python:0-3.10-bullseye`. Looks like the problem might be on my private registry side. 

Closing this for now, thanks for looking into it.

**Comment by floresjma** [comment]
I did further investigation on my side and the tags I shared before. I was wondering if this could be related that, for example, the Python image with tag `0-3.10-bullseye` and `0.204.5-3.10-bullseye` are OCI images whereas `0.204.4-3.10-bullseye` is not?

For example:

```ssh
docker buildx imagetools inspect mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye
Name:      mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:cf041df2088399d42393b350c5f78dfadf3242e1fdecaeb9f3937796832b2bdc
           
Manifests: 
  Name:        mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye@sha256:4140139ddd6ea6f0192abb5d2cb07783fdcdb1f2ec9199aa7b1748667eb08729
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/amd64
               
  Name:        mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye@sha256:276b3e6ab551c21e2ba3240ed595a8940194f17cda9742f0e01753f6b65be0f5
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/arm64
               
  Name:        mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye@sha256:a1b0a7ff4176a17bbbd37c19180ceb794d3fe841e72755417db55b1bf124025b
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:4140139ddd6ea6f0192abb5d2cb07783fdcdb1f2ec9199aa7b1748667eb08729
    vnd.docker.reference.type:   attestation-manifest
               
  Name:        mcr.microsoft.com/devcontainers/python:0.204.5-3.10-bullseye@sha256:f4a5be82af4ddefa092c40a7307fdc1b4fa42b1c9ffee7c477ce8d38d63a10b2
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations: 
    vnd.docker.reference.digest: sha256:276b3e6ab551c21e2ba3240ed595a8940194f17cda9742f0e01753f6b65be0f5
    vnd.docker.reference.type:   attestation-manifest
```

See MediaType: `application/vnd.oci.image.index.v1+json`. See that `docker buildx imagetools inspect mcr.microsoft.com/devcontainers/python:0.-3.10-bullseye` gives me a similar output.

```ssh
docker buildx imagetools inspect mcr.microsoft.com/devcontainers/python:0.204.4-3.10-bullseye
Name:      mcr.microsoft.com/devcontainers/python:0.204.4-3.10-bullseye
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:b3cadaf960d7f6d464890c53716df4bcc71b176abcb6ab12604e0cc78926a4db
           
Manifests: 
  Name:      mcr.microsoft.com/devcontainers/python:0.204.4-3.10-bullseye@sha256:e5ff28e9e17b8ee174a9103062a23b1734ee72777b424506fb9d5dcabe28c359
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      mcr.microsoft.com/devcontainers/python:0.204.4-3.10-bullseye@sha256:280f714e0d88bd13533d1d132d8db5678a75c470b0753d4edac86e80e4c82b41
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

See Name: `mcr.microsoft.com/devcontainers/python:0.204.4-3.10-bullseye`

Was that change of `MediaType` to OCI introduced then perhaps? Could that explain why my private registry cannot pull the image?

**Comment by samruddhikhandale** [comment]
> Was that change of MediaType to OCI introduced then perhaps? Could that explain why my private registry cannot pull the image?

Yep @floresjma, great findings! looks like a change related to support OCI 1.1 by the open containers team - https://toddysm.com/2023/01/05/oci-artifct-manifests-oci-referrers-api-and-their-support-across-registries-part-1/

From https://github.com/opencontainers/image-spec/blob/main/image-index.md, the `MediaType` is now `application/vnd.oci.image.index.v1+json` which seems to have recently modified.

Also, the devcontainer CLI was recently modified to support this - https://github.com/devcontainers/cli/pull/393

**Comment by floresjma** [comment]
Thanks for confirming. 

Perhaps, it could be good to include somewhere in the docs that the images are OCI format? As some older versions of registries don't support OCI format. Happy to contribute to that doc update if you think that's needed.

**Comment by samruddhikhandale** [comment]
Unfortunately, this change wasn't made by us, but by the image registries. MCR/DockerHub/ACR recently updated certain images in the registry to make them OCI-compliant. Looks like a change related to support for OCI 1.1 https://toddysm.com/2023/01/05/oci-artifct-manifests-oci-referrers-api-and-their-support-across-registries-part-1/

**Comment by floresjma** [comment]
Thank you for the detailed response.
