### ISSUE TITLE
`mcr.microsoft.com/vscode/devcontainers/universal` does not work on Apple Silicon

### ISSUE THREAD

**Issue by alexec** [devcontainers/images#454]
This image cannot be used on Apple Silicon:

```bash
➜  argo-workflows git:(master) devcontainer up --workspace-folder . --prebuild                             
[9 ms] @devcontainers/cli 0.30.0. Node.js v19.7.0. darwin 22.3.0 arm64.
Error: Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal
    at gie (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1939:1355)
    at R7 (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1939:1291)
    at async Sie (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1945:2093)
    at async Vf (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1945:3241)
    at async soe (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:17324)
    at async ioe (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:17065)
{"outcome":"error","message":"Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal","description":"An error occurred setting up the container."}
```

It runs:

```bash
docker inspect --type image mcr.microsoft.com/vscode/devcontainers/universal
```

But this image is not available:

```bash
➜  argo-workflows git:(master) docker pull mcr.microsoft.com/vscode/devcontainers/universal
Using default tag: latest
latest: Pulling from vscode/devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I tried to fix with this in the `Dockerfile`:

```Dockerfile
FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/universal
```

There are two problems here:

1. The image is not available for Apple Silicon
2. `devcontainer` CLI does not respect the `--platform` parameter.

**Comment by alexec** [comment]
I have a work-around. Do not build Docker image, use features:

```
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    "features": {
        "ghrc.io/ghcr.io/devcontainers/features/go": "latest",
        "ghrc.io/ghcr.io/devcontainers/features/node": "latest"
    },
```

**Comment by samruddhikhandale** [comment]
As mentioned in https://github.com/devcontainers/images/tree/main/src/universal#summary, currently, the `universal` image is only supported for `x86-64` architecture. 

`universal` image is based on [`focal` image](https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/Dockerfile#L6). As mentioned in https://github.com/microsoft/vscode-dev-containers/issues/558, we have no plans for arm64 support for Focal or Buster image nor other distros like centos:8 that experience random crashing. See https://github.com/microsoft/vscode-dev-containers/issues/558#issuecomment-905117722 for details.

We have an [issue open](https://github.com/devcontainers/images/issues/277#issuecomment-1358184604) which updates the `universal` image to use `jammy` (for which we support aarch64/arm64 arch). This issue will be resolved then.

**Comment by alexec** [comment]
Sure. You could change the name for "universal" to something that doesn't suggest it is universal?

**Comment by samruddhikhandale** [comment]
> You could use it with Apple Silicon if you were allowed to specify the "platform", but that is not possible. Is that a feature enhancement?

> FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/universal

I think `FROM --platform ...` can only be helpful if the `universal` image was published with multi-arch support. Unfortunately, it is currently not supported, hence, it's not expected to work 😓 

> FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy

However, this ☝️ should work as `base:jammy` is published/supported for `x86-64 and aarch64/arm64`.
