### ISSUE TITLE
universal:2.1-focal failing to build

### ISSUE THREAD

**Issue by jdcoldsmith** [devcontainers/images#466]
Hi!

When trying to use the `mcr.microsoft.com/devcontainers/universal:2.1-focal` or the `mcr.microsoft.com/devcontainers/universal:2.1.5` images I get a `Failed to create container` error.  I have attached the `creation.log` file.

Thank you for your help!
[creation.log](https://github.com/devcontainers/images/files/10874027/creation.log)

**Comment by jdcoldsmith** [comment]
Thank you @samruddhikhandale! We will use the most recent `universal` image and will use 'nvm' to change our node version to the one we want.

**Comment by phanquochoa19om** [comment]
> Hi!
> 
> When trying to use the `mcr.microsoft.com/devcontainers/universal:2.1-focal` or the `mcr.microsoft.com/devcontainers/universal:2.1.5` images I get a `Failed to create container` error. I have attached the `creation.log` file.
> 
> Thank you for your help! [creation.log](https://github.com/devcontainers/images/files/10874027/creation.log)
