### ISSUE TITLE
Switch default debian version to bullseye

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/images#474]
Are there any plans to change the default Debian version of each language to Bullseye?
I was trying to do a multi-architecture build and stumbled because arm64 was not in the default variant.
https://github.com/PRQL/prql/pull/2025#issuecomment-1455503577

It is quite surprising that the default is still Buster since it has been many months since Bullseye was released.

**Comment by samruddhikhandale** [comment]
I believe we have default as `bullseye` and it supports arm64. 

> From https://github.com/PRQL/prql/pull/2025#issuecomment-1455503577

The rust image has `latest`as `bullseye` see [here](https://github.com/devcontainers/images/blob/main/src/rust/manifest.json#L8) 

Also, all the `bullseye` tags support arm64, see [here](https://github.com/devcontainers/images/blob/main/src/rust/manifest.json#L11-L14)

> Looks like you are pulling mcr.microsoft.com/devcontainers/rust:${VERSION}-1

https://github.com/devcontainers/images/blob/main/src/rust/manifest.json#L24 Looks like the tags didn't update with the switch to `bullseye`. I'll fix this, thanks for reporting.

**Comment by samruddhikhandale** [comment]
Refer to https://github.com/microsoft/vscode-dev-containers/issues/558 for details on why focal and buster images don't support arm64

**Comment by samruddhikhandale** [comment]
Closing as completed with latest release! ⚡
