### ISSUE TITLE
[Feature Request] Add support for Julia?

### ISSUE THREAD

**Issue by jmuchovej** [devcontainers/images#480]
👋 I've been poking around `devcontainers` for a bit and saw `.../devcontainers/universal` which comes with myriad languages, but notably is missing `julia`. So I'm wondering – **would it be possible for upstream `universal` (and perhaps a language-specific) container to also come with `julia`?**

I know that `julia` isn't as widely used as `python`, `(java|type)script`, `java`, and friends (just using [stargazers][stargazers.jl] and [Julia extension installs][extension.jl] as a proxy), but it's a growing language (especially in scientific research), so having a base image for `devcontainers` would be amazing.

I'm also willing to open a PR to get this done, but wanted to check if it's something `devcontainers` would be open to accepting/supporting as a base `devcontainer` image.

[stargazers.jl]: https://github.com/julialang/julia/stargazers
[extension.jl]: https://marketplace.visualstudio.com/items?itemName=julialang.language-julia

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thank you for your insights and for offering help, we appreciate it. ✨ 

However, according to the [contribution guidelines](https://github.com/devcontainers/images#how-can-i-contribute), we only plan to support the [current list of published images](https://github.com/devcontainers/images/tree/main/src). 

For the `universal` image, we include the most widely used tools/languages/frameworks. According to https://survey.stackoverflow.co/2022/, `julia` seems to be less popular than most of the languages we currently support. 
Hence, I think we shouldn't add it to the `universal` image. (@bamurtaugh / @Chuxel  would appreciate your thoughts here)

<img width="845" alt="image" src="https://user-images.githubusercontent.com/24955913/223588507-7f84a197-d6d2-46e0-8cc7-136c9615c7f3.png">

Looks like we have a `Julia` Feature contributed by the community, see [here](https://containers.dev/features). @jmuchovej  Have you thought of using that?

**Comment by eitsupi** [comment]
Note that there is a Julialang "official" Julia Feature, although it is not yet registered in the devcontainers index.
https://github.com/JuliaLang/devcontainer-features/tree/main/src/julia

Discussion on this can be found in the previous repository microsoft/vscode-dev-containers#1114.
In short, Julia installs so fast that it would be better for users to install it with Features as needed, rather than spending the effort to manage pre-built images, I think.

cc @davidanthoff

**Comment by jmuchovej** [comment]
> Note that there is a Julialang "official" Julia Feature, although it is not yet registered in the devcontainers index.

I see. I didn’t realize. 😅

> In short, Julia installs so fast that it would be better for users to install it with Features as needed, rather than spending the effort to manage pre-built images, I think.

That makes sense, though unless `devcontainer` features can be baked into a prebuilt container, the same environment couldn’t be used on research clusters (which is where I saw the main value in prebuilt container images).

**Comment by samruddhikhandale** [comment]
Feel free to reopen if needed, thanks!
