### ISSUE TITLE
PHP: ability to change port

### ISSUE THREAD

**Issue by mmghv** [devcontainers/images#497]
I'm using a PHP container as a backend, my frontend runs on port `8080` by default so I need to change apache port for the backend, I'm able to do that with this command :

```json
    "onCreateCommand": "sudo perl -0777 -i -pe 's/Listen 80\nListen 8080/Listen 5000/' /etc/apache2/ports.conf"
```

But I still get port `8080` reserved by vscode which causes problems with my frontend, I have to manually remove it from vscode everytime before running my frontend container.

It is reserved because of this setting in the base `.devcontainer.json` :

```json
    "forwardPorts": [
        8080
    ],
```

Removing this setting from the base image will solve the problem, apache port will get auto-forwarded anyways so it's not really needed.

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/images/pull/498

**Comment by mmghv** [comment]
How do I update the image I have? when I rebuild the container I get the same image even if I remove the base images before building the container.

**Comment by samruddhikhandale** [comment]
That's strange. Can you remove the images from your docker cache and retry?

**Comment by mmghv** [comment]
I removed the images with :

```bash
docker image prune -a -f
```

But still got the old image, I had to run this command to remove the build cache :

```bash
docker builder prune -a -f
```

The new `php-8` container had the port removed after I commented the `forwardPorts` option, but the `php-7.4` container still had the port `8080` forwarded, I guess you don't update the old images.
