### ISSUE TITLE
Getting error /tmp on WSL-2

### ISSUE THREAD

**Issue by mwoodpatrick** [devcontainers/images#502]
On latest WSL-2 I'm running:
 
`docker rm westie-dev`

and getting

```
docker run --name westie-dev -it mcr.microsoft.com/devcontainers/universal:linux /bin/bash
westie-dev
mount: /tmp: permission denied.
```

Any pointers on what I'm doing wrong or how to debug

**Comment by samruddhikhandale** [comment]
Hi 👋 

For the `universal` image, we need to pass the `init` and `privileged` flags, @mwoodpatrick can you try this command? 👇 

> docker run --name westie-dev -it --init --privileged mcr.microsoft.com/devcontainers/universal:linux /bin/bash

**Comment by mwoodpatrick** [comment]
Many thanks, that worked
