### ISSUE TITLE
Any plan for Ruby 2.7.8?

### ISSUE THREAD

**Issue by ryush00** [devcontainers/images#526]
Ruby Security Update 2.7.8 has been released at March 30, but the mcr.microsoft.com/devcontainers/ruby:2.7 image seems to be stuck at 2.7.7.

I would like to know if there are no more updates planned as it is EOL.(#447)

Thank you! :)

## Reference link
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/

**Comment by samruddhikhandale** [comment]
Hi,

In order to be in sync with the ruby releases, we will do one last images release to update to ruby 2.7.8 and further deprecate it.

**Comment by samruddhikhandale** [comment]
Closing as released the last version of ruby 2.7 - It would be deprecated again now.
