### ISSUE TITLE
Anaconda image compatible with M1 Mac and popular python packages (scipy, numpy, etc)

### ISSUE THREAD

**Issue by nsuberi** [devcontainers/images#527]
Hello! My team is using docker with M1 Macs, and attempting to install an environment that includes scipy.

We are using this base image: FROM --platform=linux/arm64 mcr.microsoft.com/devcontainers/anaconda:0-3

We notice issues trying to use pip to install certain packages.... some versions of numpy were giving us issues before, and now we're getting failures with scipy.

Below is the error we're seeing w/ scipy... further down, you will see the entire requirements.txt we attempted to install with `pip install -r requirements.txt`. This is in a conda environment with python 3.8.16 (conda environment setup details below).

Any help appreciated!
Thank you,
~ Nathan

Collecting scipy==1.9.2 (from -r /workspaces/mme003/src/RESTING_ORDER_SHAPE_PRDCN/app/trial_requirements.txt (line 1))
  Using cached https://artifactory.finra.org/artifactory/api/pypi/python_repo/packages/packages/17/07/68df07679ec4a4a24bff00147a14908aa73e9e8912d142886e8d0e1e3d64/scipy-1.9.2.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3
      Build dir: /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3/.mesonpy-9i8fsprs/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.2
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:49:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3/.mesonpy-9i8fsprs/build/meson-logs/meson-log.txt
      + meson setup --prefix=/opt/conda/envs/my_env /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3 /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3/.mesonpy-9i8fsprs/build --native-file=/tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`requirements.txt`
scipy==1.9.2

`Conda environment setup`
  && conda activate base \
  && conda config --add channels conda-forge \
  && conda config --set channel_priority strict \
  && conda create -y -n my_env python=3.8.16 pip \
  && conda activate $ENV_NAME \
  && conda config --set pip_interop_enabled true \

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting the issue. @alexander-smolyakov can you help investigate, thank you!

**Comment by alexander-smolyakov** [comment]
Hey @nsuberi, I'm currently looking into this issue. Could you please provide the following information:
- The issue appears only for specific Python packages version, right?
- The issue appears only on M1-based machines?
- Could you please share the entire log from this message? `  A full log can be found at /tmp/pip-install-g3y9lkqy/scipy_2c3494afdc5b4edd9d0c7abaa35c2ed3/.mesonpy-9i8fsprs/build/meson-logs/meson-log.txt`

**Comment by nsuberi** [comment]
Hi @alexander-smolyakov , yes - the issue only appears for specific Python packages.

It appears that for python 3.8 there is not a pre-built scipy image that works on aarch64 (M1 Mac architecture)

You can see in the error logs that it is attempting to build fortran code from the .tar.gz version of the package:
[scipy-1.9.2.tar.gz](https://artifactory.finra.org/artifactory/api/pypi/python_repo/packages/packages/17/07/68df07679ec4a4a24bff00147a14908aa73e9e8912d142886e8d0e1e3d64/scipy-1.9.2.tar.gz) (42.1 MB)

The issue is resolved when we upgrade to using python 3.9. 

Thank you for looking into it!
