### ISSUE TITLE
dotnet:0-7.0 includes VSCode extension dbaeumer.vscode-eslint

### ISSUE THREAD

**Issue by StephenCleary** [devcontainers/images#541]
Is this deliberate/unavoidable? It just seems weird to start a dotnet devcontainer and see the VSCode in the container installing the dbaeumer.vscode-eslint extension. VSCode says it has 250ms activation time.

**Comment by bamurtaugh** [comment]
@samruddhikhandale @Chuxel do you have any further context on this one? I agree it seems a bit unusual.

**Comment by samruddhikhandale** [comment]
For the dotnet image, we are adding the node Feature [to the devcontainer.json](https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/devcontainer.json#L14-L16) - which installs nvm for future use. However, the node Feature adds the eslint extension (see [here](https://github.com/devcontainers/features/blob/main/src/node/devcontainer-feature.json#L40)) which ends up getting installed with the `dotnet` image.

From the [docs](https://github.com/devcontainers/images/blob/main/src/dotnet/README.md#installing-nodejs-or-the-azure-cli), 👇 

> Given JavaScript front-end web client code written for use in conjunction with an ASP.NET back-end often requires the use of Node.js-based utilities to build, this container also includes nvm so that you can easily install Node.js.

That's the reason behind adding the `node` Feature, however, I wonder if we should remove the Feature and install `nvm` directly. We have an issue open for the same request --> https://github.com/devcontainers/images/issues/424

**Comment by bamurtaugh** [comment]
Ah this makes sense, thank you! I think we can close this issue and instead track in https://github.com/devcontainers/images/issues/424. 

@StephenCleary if your ask is different that https://github.com/devcontainers/images/issues/424 though, please just let us know. Thanks!
