### ISSUE TITLE
Anaconda: Support debian-12 (bookworm)

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#616]
Depends on [continuumio/anaconda3](https://hub.docker.com/r/continuumio/anaconda3)

- [ ] Open a PR 
- [ ] Create a release

**Comment by samruddhikhandale** [comment]
Blocked by https://hub.docker.com/r/continuumio/anaconda3 as it needs to add support for `bookworm`.


![Image](https://github.com/devcontainers/images/assets/24955913/304ec3ce-a803-45e3-a315-d694d3bc29c2)


Once it's available, we'd need a major version bump of the image. More info in here https://github.com/devcontainers/images/issues/607

**Comment by gauravsaini04** [comment]
been updated to bookworm now : 
```
(base) root@1da8bb3a55f5:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by samruddhikhandale** [comment]
Thanks @gauravsaini04. I'd look into the release process now.

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Due to https://github.com/devcontainers/images/issues/1122, can you help update the Templates and sync MCR docs with this new info? 

We need to pin to this new major version `1` for Templates ([eg](https://github.com/devcontainers/templates/blob/main/src/anaconda/.devcontainer/Dockerfile#L1))

**Comment by gauravsaini04** [comment]
PR's were merged to the codebases

**Comment by Arman8434317** [comment]
> been updated to bookworm now : 
> ```
> (base) root@1da8bb3a55f5:/# cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> ```

**Comment by Skaillet91** [comment]
Skaillet91:main
