### ISSUE TITLE
Rust: Support debian-12 (bookworm)

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#617]
Depends on https://hub.docker.com/_/rust

- [x] Open a PR 
- [x] Create a release
- [ ] Update templates (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [ ] Update https://mcr.microsoft.com/en-us/catalog?search=dev%20container docs

**Comment by samruddhikhandale** [comment]
Closing as completed 🚀

**Comment by Juancanico5** [comment]
> Depende de https://hub.docker.com/_/rust
> 
> * [x] Abrir un PR
> * [x] Crear una versión
> * [ ] Actualizar plantillas (si es necesario)
> * [x] Actualización [[Seguimiento] Compatibilidad con imágenes, obsolescencia/fechas EOL ](https://github.com/devcontainers/images/issues/90)[ #90](https://github.com/devcontainers/images/issues/90)[](https://github.com/devcontainers/images/issues/90)
> * [ ] Actualización https://mcr.microsoft.com/en-us/catalog?search=dev%20container docs
