### ISSUE TITLE
Miniconda: Support debian-12 (bookworm)

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#621]
Depends on https://hub.docker.com/r/continuumio/miniconda3

- [ ] Open a PR 
- [ ] Create a release

**Comment by samruddhikhandale** [comment]
Blocked by https://hub.docker.com/r/continuumio/miniconda3 as it needs to add support for `bookworm`.


![Image](https://github.com/devcontainers/images/assets/24955913/177e6766-5a71-4abc-9d8a-a00c6409b2fc)

Once it's available, we'd need a major version bump of the image. More info in here https://github.com/devcontainers/images/issues/607

**Comment by gauravsaini04** [comment]
The base image for miniconda i.e. continuumio/miniconda3 has been updated to debian - 12 ( bookworm ) 
```
		(base) root@4a987cfa50fe:/# cat /etc/os-release
		PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
		NAME="Debian GNU/Linux"
		VERSION_ID="12"
		VERSION="12 (bookworm)"
		VERSION_CODENAME=bookworm
		ID=debian
		HOME_URL="https://www.debian.org/"
		SUPPORT_URL="https://www.debian.org/support"
		BUG_REPORT_URL="https://bugs.debian.org/"
		(base) root@4a987cfa50fe:/# ```

**Comment by VincentDondain** [comment]
Waiting to be released

**Comment by gauravsaini04** [comment]
pr was merged

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Due to https://github.com/devcontainers/images/issues/1122, can you help update the Templates and sync MCR docs with this new info? 

We need to pin to this new major version `1` for Templates

**Comment by gauravsaini04** [comment]
> @gauravsaini04 Due to #1122, can you help update the Templates and sync MCR docs with this new info?
> 
> We need to pin to this new major version `1` for Templates

have raised pr's https://github.com/devcontainers/templates/pull/269 and https://github.com/microsoft/mcrdocs/pull/47485 for templates and mcr docs resp.

**Comment by gauravsaini04** [comment]
PR's were merged to the codebases
