### ISSUE TITLE
MSSQL: Alpine image support

### ISSUE THREAD

**Issue by thevedicdeveloper** [devcontainers/images#644]
Hi,

Can we have MSSQL Alpine image support? We already have an alpine base image. We can use it to create an MSSQL image.

we can use Microsoft OBDC driver for alpine from [here](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline#alpine-linux)

```dockerfile
#Download the desired package(s)
curl -O https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/msodbcsql18_18.2.2.1-1_amd64.apk
curl -O https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/mssql-tools18_18.2.1.1-1_amd64.apk


#(Optional) Verify signature, if 'gpg' is missing install it using 'apk add gnupg':
curl -O https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/msodbcsql18_18.2.2.1-1_amd64.sig
curl -O https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/mssql-tools18_18.2.1.1-1_amd64.sig

curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
gpg --verify msodbcsql18_18.2.2.1-1_amd64.sig msodbcsql18_18.2.1.1-1_amd64.apk
gpg --verify mssql-tools18_18.2.1.1-1_amd64.sig mssql-tools18_18.2.1.1-1_amd64.apk


#Install the package(s)
sudo apk add --allow-untrusted msodbcsql18_18.2.2.1-1_amd64.apk
sudo apk add --allow-untrusted mssql-tools18_18.2.1.1-1_amd64.apk
```

**Comment by thevedicdeveloper** [comment]
closing... template already exist [here](https://github.com/devcontainers/templates/tree/main/src/dotnet-mssql)

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the suggestion, we appreciate it. However, the `devcontainers/images` repo only accepts improvements and bug fixes for the [current set of maintained Images](https://github.com/devcontainers/images/blob/main/src). 

We don't have any current plans of supporting a new image, feel free to look at https://github.com/devcontainers/images#how-can-i-contribute for more information.

// cc @bamurtaugh for any other thoughts.

**Comment by bamurtaugh** [comment]
Thanks so much for opening @thevedicdeveloper and for tagging me @samruddhikhandale!

@thevedicdeveloper we definitely welcome you to create and contribute your own images, Features, and Templates! If you have any questions, please let us know.

**Comment by thevedicdeveloper** [comment]
does it mean I can work on it and create a pull request for this feature? @bamurtaugh

**Comment by bamurtaugh** [comment]
We absolutely encourage you to create any additional resources, though you'd host it in your own repo rather than this repo, as @samruddhikhandale shared above (this repo is just for a small subset of possible images). There is more info on this process in our docs: https://github.com/devcontainers/images#how-can-i-contribute.

If you create and self-host Templates or Features, you can open a PR to contribute them to our community index! There's info on this in our docs too: https://containers.dev/collections, https://containers.dev/implementors/templates-distribution/, https://containers.dev/implementors/features-distribution/.

**Comment by thevedicdeveloper** [comment]
thanks for the detailed information @bamurtaugh
