### ISSUE TITLE
Support [Image Name] [variant/version] scheduled for [date]

### ISSUE THREAD

**Issue by 0918039995** [devcontainers/images#652]
Depends on [add a reference link here]

- [ ] Open a PR 
- [ ] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by 0918039995** [comment]
，，，。。

**Comment by samruddhikhandale** [comment]
Looks like an accident, closing! Feel free to reopen with details, if necessary.
