### ISSUE TITLE
Where are the Dockerfiles? 😄

### ISSUE THREAD

**Issue by dpprdan** [devcontainers/images#653]
The https://github.com/devcontainers/images/blob/main/src/python/README.md reads:

> Alternatively, you can use the contents of `Dockerfile` to fully customize the your container's contents or build for a container architecture the image does not support.

I am assuming that this refers to a Dockerfile in this repo? However I cannot find it anywhere (apart from https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/Dockerfile which doesn't seem to be complete? E.g. I don't see where [the dependencies](https://github.com/devcontainers/images/blob/99acaadbc99a6211b3e5452203ffc90b9e63ae75/src/python/manifest.json#L95) are added). 

Put differently: Is it possible to view (example-)Dockerfiles of the final images?

**Comment by samruddhikhandale** [comment]
Hi 👋 

> I am assuming that this refers to a Dockerfile in this repo? 

Yes, that statement is pointing to the [Dockerfile](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/Dockerfile) you mentioned. 

> However I cannot find it anywhere (apart from https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/Dockerfile which doesn't seem to be complete?

Dev container Features are doing rest of the work, see [here](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/devcontainer.json#L6-L20). Look at https://containers.dev/implementors/features/ for more information.

> E.g. I don't see where [the dependencies](https://github.com/devcontainers/images/blob/99acaadbc99a6211b3e5452203ffc90b9e63ae75/src/python/manifest.json#L95) are added).

They are installed by the Python Feature, in [here](https://github.com/devcontainers/features/blob/main/src/python/install.sh#L29).

@dpprdan Let me know if that helps clear your doubts, or happy to answer any other questions.

> Alternatively, you can use the contents of Dockerfile to fully customize the your container's contents or build for a container architecture the image does not support.

@Chuxel We copied over the Readme file from https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3 when Features didn't exist and `base.dockerfile` was doing all the work. I wonder if we should replace current statement to 👇 (to avoid confusions) or remove that line? Any thoughts? // cc @bamurtaugh 

> Alternatively, you can use the contents of <s> `Dockerfile`</s> `devcontainer` to fully customize the your container's contents or build for a container architecture the image does not support.

**Comment by bamurtaugh** [comment]
I like your idea to update the wording @samruddhikhandale! Maybe something like:

```
Alternatively, you can use the Dockerfile in this template's image to fully customize the your container's contents or build for a container architecture the image does not support. The image's definition, including its Dockerfile, can be found in the [devcontainers/images](https://github.com/devcontainers/images/tree/main/src) repo.
```

I kept the last sentence more general to avoid needing to link every readme uniquely, though if we're willing to do that and don't think the links will break, that'd also probably help.

**Comment by samruddhikhandale** [comment]
@bamurtaugh we could dynamically update `Dockerfile ` to point to the actual file (eg. [Dockerfile](.devcontainer/Dockerfile)).

My main question is, if we should replace `Dockerfile` word to `.devcontainer` as we use the entire folder to create/customize the dev container. With @dpprdan, I believe he was confused because we mention one should only update `Dockerfile`, but the actual logic of this image is in `.devcontainer.json` file (ie. python Feature)🤔

**Comment by bamurtaugh** [comment]
> My main question is, if we should replace Dockerfile word to .devcontainer as we use the entire folder to create/customize the dev container.

Oh got it! That's a great point. I'm in favor of updating to `.devcontainer` with the reasoning you mention.

**Comment by dpprdan** [comment]
@samruddhikhandale Thanks, that is really helpful. 

I took the liberty to propose a few more changes in #656, maybe you two want to have a look at that? 
Feel free to incorporate those changes (or the ones you find worthwhile) into #654.
