### ISSUE TITLE
Can't open any dev container - code-server causes Segmentation Fault (arm64/Apple Silicon)

### ISSUE THREAD

**Issue by leclerc91** [devcontainers/images#660]
Type: **Bug**

- VS Code Version: 1.80.1
- OS Version: macOS Ventura 13.4.1 (c)
- Local chip architecture: arm64/Apple Silicon (Apple M1 Pro)

**Docker Desktop**
- Docker Engine: v24.0.2
- File sharing implementation for containers: VirtioFS
- Use Virtualization Frameworks: Enabled
- No beta features enabled/selected

### Steps:
1. Run the **Dev Containers: Open Folder in Container**... command from the Command Palette (F1) or quick actions Status bar item and pick any project folder.
2. As a dev container configuration template select **Debian - bullseye**.
3. Do not pick any additional Features and click OK.

At that point, VSCode downloads the image and starts preparing the dev container. It then stops with the message "An error occurred setting up the container" and showing 
```
Command failed: /home/vscode/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/vscode/.vscode-server/data/Machine/.connection-token-74f6148eb9ea00507ec113ec51c489d6ffb4b771 --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --start-server 
Segmentation fault
Exit code 139
```

Additionally, I started the container created by VSCode and run
`sh /home/vscode/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/code-server`, which causes again **Segmentation fault**. This makes me think that the problem is not caused by the parameters used by VSCode.

--

I first encountered this problem last Friday (14 July) and since then I am unable to open any dev containers. Before that, I never had any problems using dev containers.
I have tried deleting all docker images, clearing the build cache, reinstalling docker, cleaning all my VSCode settings and reinstalling VSCode and nothing seems to fix it.

**Comment by leclerc91** [comment]
The problem only happens with **VSCode 1.8.1** (`74f6148eb9ea00507ec113ec51c489d6ffb4b771`).

Running the version of `node` in `/home/vscode/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node` causes the **Segmentation Fault**, which is launched by the script `/home/vscode/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/code-server`.


I have checked the version of Node.js used in the dev containers in previous releases of VSCode, such as

**VSCode v1.80** (`660393deaaa6d1996740ff4880f1bad43768c814`)
`/vscode/vscode-server/bin/linux-arm64/660393deaaa6d1996740ff4880f1bad43768c814/node`

**VSCode v1.79.2** (`695af097c7bd098fbf017ce3ac85e09bbc5dda06`)
`/vscode/vscode-server/bin/linux-arm64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node`

and they work fine.

Is the version of Node.js in the dev containers for the latest release of VSCode different?

**Comment by bamurtaugh** [comment]
Thanks for opening.

> Is the version of Node.js in the dev containers for the latest release of VSCode different?

cc @chrmarti for thoughts.

**Comment by chrmarti** [comment]
Cannot reproduce. Maybe an issue with the downloaded tar. Could you retry with 1.80.2?

**Comment by leclerc91** [comment]
It is working fine again in VSCode `1.80.2`! :)

Nevertheless, it wasn't a problem with the downloaded tar, it is still happening in the version `1.80.1`. I just downloaded the version `1.80.1` to confirm this.

In fact, trying to open the file `/vscode/vscode-server/bin/linux-arm64/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node` in version `1.80.2` still results in the **Segmentation Fault**.

**Comment by leclerc91** [comment]
Great, that has indeed solved the problem! 🙂
Thank you!
