### ISSUE TITLE
[Image Name] [variant/version] EOL scheduled for [date]

### ISSUE THREAD

**Issue by LONCHHAIHONG** [devcontainers/images#732]
Depends on [add a reference link here]

- [ 5156830368918554] Create a release (if necessary - which ensures images are up to date before deprecating )
- [ 001645559] Open a PR 
- [001645559 ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [001645559 ] Update https://github.com/devcontainers/images/issues/90
- [001645559 ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by LONCHHAIHONG** [comment]
ID: 001645559

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
