### ISSUE TITLE
How can there be no windows variant of the dotnet image?

### ISSUE THREAD

**Issue by RollsChris** [devcontainers/images#733]
I'm either missing something or it is just really strange there isn't a windows version of mcr.microsoft.com/devcontainers/dotnet?

**Comment by bamurtaugh** [comment]
Hi there, thanks for filing! Dev containers only support Linux containers, so there won't be any Windows-based configurations in this repo. There's a feature request on the Dev Containers extension that's been used to track interest in such support: https://github.com/microsoft/vscode-remote-release/issues/445.

Please feel free to continue discussion in that issue https://github.com/microsoft/vscode-remote-release/issues/445. Thank you!
