### ISSUE TITLE
Github codespaces short link redirects to the old repo

### ISSUE THREAD

**Issue by iemejia** [devcontainers/images#738]
The short link used in the documentation:
https://aka.ms/ghcs-default-image
is still redirecting to the old repo
https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux
It should probably redirect to this one
https://github.com/devcontainers/images/tree/main/src/universal/

**Comment by samruddhikhandale** [comment]
Hi 👋 

Good catch, thanks for reporting the bug. 

@bamurtaugh wondering, if you have access to update the `https://aka.ms/ghcs-default-image` link to `https://github.com/devcontainers/images/tree/main/src/universal/` ?

**Comment by bamurtaugh** [comment]
Just updated, thanks!
