### ISSUE TITLE
Support [Image Name] [variant/version] scheduled for [date]

### ISSUE THREAD

**Issue by berryspace1014** [devcontainers/images#745]
Depends on [add a reference link here]

- [x] Open a PR 
- [ ] Create a release
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
