### ISSUE TITLE
[ubuntu-base] [ubuntu-22.04] ssh keys don't work in ubuntu-base image

### ISSUE THREAD

**Issue by brianwatersmanna** [devcontainers/images#768]
I am creating a simple devcontainer based on the base images stored here.

I have tried two images:
- mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
- mcr.microsoft.com/vscode/devcontainers/base:bullseye

Using the bullseye image, ssh keys are passed from the host automatically.

In the ubuntu-22.04 image, they are not?

I have checked the ubuntu-20.04 image and they work fine also. Seems to be isolated to the 22.04 image?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting the issue. Looks like it's similar to problem mentioned in https://github.com/devcontainers/images/issues/650#issuecomment-1692898082

@alexander-smolyakov Can you help investigate this issue? Thank you!

**Comment by akutruff** [comment]
I just hit this same issue.  It's very strange since I can see my keys show up in the vs-code terminal when i run `ssh-add -l`  however when I try to do `ssh -T git@github.com` or any other git operations I get a `permission denied (public key)` error

**Comment by Roemer** [comment]
Same with debian:bookworm. `ssh-add -l` correctly returns the identity but authenticating with git or ssh fails with an error message somewhere in the log: `get_agent_identities: ssh_fetch_identitylist: communication with agent failed`

It seems to be some kind of incompatibility with different OpenSSH versions, see also https://github.com/microsoft/vscode-remote-release/issues/7525

**Comment by samruddhikhandale** [comment]
Thanks @Roemer for pointing it out. Closing as this looks like an upstream issue! 

Might be worth looking at https://github.com/microsoft/vscode-remote-release/issues/7525#issuecomment-1354742843 and upgrading OpenSSH for Windows.
