### ISSUE TITLE
Missing images for Go 1.21

### ISSUE THREAD

**Issue by Jomik** [devcontainers/images#783]
I see that `mcr.microsoft.com/devcontainers/go:1.21` is mentioned on the readme, https://github.com/devcontainers/images/blob/52478448feafce54fdbe69a49236ab5ef3afde1b/src/go/README.md

But it does not seem to be available when I look in [MCR](https://mcr.microsoft.com/en-us/product/devcontainers/go/about)

**Comment by Jomik** [comment]
@samruddhikhandale the image mentioned in the readme doesn't exist. There is no `mcr.microsoft.com/devcontainers/go:1.21` even though the readme mentions it, so we have to choose an OS 👍

**Comment by samruddhikhandale** [comment]
I see your point now, thanks for reporting. It was a bug with our release builds. https://github.com/devcontainers/images/pull/784 fixes it, it should be updated with next release.
