### ISSUE TITLE
Alpine 3.19 scheduled for Nov

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#786]
Depends on https://hub.docker.com/_/alpine/tags?page=1&name=3.19

- [x] Open a PR 
- [x] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update https://github.com/devcontainers/images/issues/90

**Comment by samruddhikhandale** [comment]
This issue is blocked because the upstream `alpine` image is not available.  Hence, we can't create an alpine 3.19 image. See https://hub.docker.com/_/alpine/tags?page=1&name=3.19

As alpine 3.19 is new, we could wait for sometime to give alpine maintainers to work through it. But, if not, we can open an issue in https://github.com/alpinelinux/docker-alpine/issues?q=

**Comment by btrepp** [comment]
Alpine 3.19 seems available now :)

**Comment by eljog** [comment]
Alpine 3.19 is now released in Dev tag - ready for a prod/latest release

**Comment by samruddhikhandale** [comment]
Closing, as completed the release 🎉 

Thanks, @eljog
