### ISSUE TITLE
Support .NET 8 scheduled for Nov 14

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#787]
Depends on [add a reference link here]

- [x] Open a PR 
- [x] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by marinasundstrom** [comment]
So there is no build with RC 2?

**Comment by samruddhikhandale** [comment]
> So there is no build with RC 2?

@marinasundstrom, unfortunately, we don't. We only add support for production ready frameworks.

**Comment by seesharprun** [comment]
Would it be out-of-bounds to create a PR to add .NET 8 support to the universal image as it's now the new LTS?

**Comment by samruddhikhandale** [comment]
> Would it be out-of-bounds to create a PR to add .NET 8 support to the universal image as it's now the new LTS?

For the `universal` image, we have the following rules defined :

- Only include LTS (or latest) releases of tools used for key scenarios
- When several LTS versions are in support, include only the latest two

Hence, updating `universal` image to support .NET versions `8` and `6` makes sense to me. 

I can help review [Update universal image to .NET 8 #855](https://github.com/devcontainers/images/pull/855) when it's ready.

**Comment by seesharprun** [comment]
Sounds good, I removed .NET 7 from the pull request and it's ready for review now.

Thanks!

**Comment by samruddhikhandale** [comment]
Closing as .Net 8 images are now released 🎉
