### ISSUE TITLE
User `node` does not have sufficient permissions for `npm i` command to succeed

### ISSUE THREAD

**Issue by MRDGH2821** [devcontainers/images#820]
I'm using this image - `mcr.microsoft.com/devcontainers/typescript-node:18` as my dev container with some features.

As per the info [here](https://github.com/devcontainers/images/tree/main/src/typescript-node) `node` user has sudo access, but I'm not talking about sudo. I'm talking about regular CLI interactions, like this:

![image](https://github.com/devcontainers/images/assets/46621001/6f840f28-08c0-49cf-aac9-98740bdb8332)

As per the screenshot, `npm` is not able to install anything because of some permission error.
I have tried different node versions, complete rebuild of dev container and in fact different computers too, for this error to go away but no luck. I have to include `sudo` keyword wherever it fails.

I tried dev container in Windows, I tried dev container in WSL, none of them work.
My current config is using dev container inside WSL. Which is thanks to WSL integration offered by Docker Desktop.

File permissions: 
![file-permissions](https://github.com/devcontainers/images/assets/46621001/dd64f8cf-c305-45bb-bc8b-bd56eb6a6030)

Additional info:
VS Code:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```
Docker in Windows 
```
Docker version 24.0.6, build ed223bc
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

I wonder if there is some other dev container configuration interfering with your setup. I tried creating a container on the image, `npm i` works fine. See 👇 

![Image](https://github.com/devcontainers/images/assets/24955913/638c8947-f5f4-48a3-b11b-ce7420ac42e9)

@MRDGH2821 will it be possible to share a sample repo where this can be reproduced? I can help investigate.

**Comment by MRDGH2821** [comment]
> Hi 👋 
> 
> I wonder if there is some other dev container configuration interfering with your setup. I tried creating a container on the image, `npm i` works fine. See 👇 
> 
> ![Image](https://github.com/devcontainers/images/assets/24955913/638c8947-f5f4-48a3-b11b-ce7420ac42e9)
> 
> @MRDGH2821 will it be possible to share a sample repo where this can be reproduced? I can help investigate. 

Use the main branch - https://github.com/MRDGH2821/Perpetual-Mechanical-Array-Bot

**Comment by samruddhikhandale** [comment]
@MRDGH2821 Can you use `postCreateCommand` instead of [onCreateCommand](https://github.com/MRDGH2821/Perpetual-Mechanical-Array-Bot/blob/main/.devcontainer/devcontainer.json#L17)? Looks like that's the root cause as `onCreateCommand` runs before the container is created. See https://containers.dev/implementors/json_schema/

I was able to run `npm i` with your config by commenting out [the following](https://github.com/samruddhikhandale/Perpetual-Mechanical-Array-Bot/commit/49ce2265f4f97b3bd17d0c0d434fa4b8121ae666)👇 

![Image](https://github.com/devcontainers/images/assets/24955913/f28fb177-a6e7-43d3-a88f-0634b048bd07)

**Comment by MRDGH2821** [comment]
Thanks for the explanation & solution!

I don't recall why I put `sudo`, must be because without `sudo` it didn't work few months back
