### ISSUE TITLE
Support PHP 8.3 scheduled for November 23

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#828]
Depends on https://hub.docker.com/_/php/tags?page=1&name=8.3-apache

- [x] Open a PR 
- [x] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by eljog** [comment]
Image has been already updated and released
Will do templates and registry updates after #827 that also updates the same PHP images
