### ISSUE TITLE
Dart container breaks when changing `VARIANT` to `3` or `latest`

### ISSUE THREAD

**Issue by j-h-a** [devcontainers/images#847]
Ok, so I think I finally find the right org/repo 🤷‍♀️
This is in relation to this container: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/dart

I see it's not migrated into this org yet, but I don't see anywhere else that's more appropriate than here...

When changing the VARIANT to 3 or latest, the `common-debian` script no longer works, failing as follows:
```
ERROR: failed to solve: process "/bin/sh -c /bin/bash /tmp/library-scripts/common-debian.sh \"${INSTALL_ZSH}\" \"${USERNAME}\" \"${USER_UID}\" \"${USER_GID}\" \"${UPGRADE_PACKAGES}\" \"true\" \"true\"" did not complete successfully: exit code: 2
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

We migrated Templates to the [devcontainers org](https://github.com/devcontainers), as part of the work on the [open dev container specification](https://containers.dev/). For more details, you can review the https://github.com/microsoft/vscode-dev-containers/issues/1589. However, it did not include the Templates which were contributed by the community and we only continued support for the official ones. 

As mentioned in https://containers.dev/templates, `Dart` Template is no longer maintained and hence, we won't be able to help with your request. We tried reaching out to the contributors, but they haven't yet to migrated it to their own repo. 

![Image](https://github.com/devcontainers/images/assets/24955913/69186177-bd35-40f5-b170-73dd5c53fcbb)

If you are interested, we would appreciate if you could add this Template in a separate repository of your control. The [devcontainers/template-starter](https://github.com/devcontainers/template-starter) repo has more guidance on self authoring them. Once you've self authored and if you'd like to share it with the community, feel free to add it to the index. 

> This is in relation to this container: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/dart

I thought we updated the READMEs with a Note to mention that they have been deprecated, and are no longer maintained. But looks like it is missing, apologies for the inconvenience. // cc @bamurtaugh
