### ISSUE TITLE
The  `rebornix.Ruby` extension is marked as deprecated

### ISSUE THREAD

**Issue by jcansdale** [devcontainers/images#870]
The [rebornix.Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) extension is marked as deprecated. It suggests moving to the [shopify.ruby-lsp](https://marketplace.visualstudio.com/items?itemName=shopify.ruby-lsp) extension instead.

![Image](https://github.com/devcontainers/images/assets/11719160/e61d81be-30e8-4dfb-b823-17de20aa1abf)

Should we update the `devcontainer.json` here?
https://github.com/devcontainers/images/blob/main/src/ruby/.devcontainer/devcontainer.json#L27

**Comment by eljog** [comment]
Apparently we already have a PR out for this https://github.com/devcontainers/images/pull/860
We have been waiting to learn more about the preferences of the community
https://github.com/devcontainers/images/pull/860/files#r1406569477
>it's certainly a trickly problem to tackle as everyone has their own set of preferences. Since I'm not sure we've seen other requests to add this extension pack, my first instinct is we leave this PR open for further community feedback.

**Comment by eljog** [comment]
#894 has removed the deprecated extension for devcontainer, and the ruby feature [here](https://github.com/devcontainers/features/blob/3ea4d6bbd7864bcf7b5a91fdeeb66e4f5a6f46c0/src/ruby/devcontainer-feature.json#L21-L27) is already installing the suggested [shopify.ruby-lsp](https://marketplace.visualstudio.com/items?itemName=shopify.ruby-lsp) extension.
🎉
