### ISSUE TITLE
Workflow `actions/workflows/push-dev.yml` failing due to npm 10.2.5 release 

### ISSUE THREAD

**Issue by barrbrain** [devcontainers/images#909]
In `src/javascript-node/.devcontainer/Dockerfile` npm is pinned to 9.8.1 but this appears to fail with a warning about a new release.

```
126.5 npm notice New major version of npm available! 9.8.1 -> 10.2.5
126.5 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
126.5 npm notice Run `npm install -g npm@10.2.5` to update!
126.5 npm notice 
```

See e.g. https://github.com/devcontainers/images/actions/runs/7377824987/job/20140378411

**Comment by eljog** [comment]
Thank you for opening this issue.
I have a PR #913 out to address it
