### ISSUE TITLE
Links on Docker Hub for (some?) tag lists/details are broken/lead to 404s

### ISSUE THREAD

**Issue by Clockwork-Muse** [devcontainers/images#911]
Clicking on a number of links on the Docker Hub devcontainer landing page produces 404s.  For instance, the link to all tags for the "base" devcontainer images attempts to point to `https://hub.docker.com/_/%60mcr.microsoft.com/devcontainers/base/tags/list` , but this page doesn't exist.  The current page, given some of the working links in this repo should be `https://mcr.microsoft.com/v2/devcontainers/base/tags/list`.
The links may point to either Docker Hub or GitHub, but either way this is unfriendly or confusing to other users.  

Note that the landing page may be out of date generally.  The page mentions that due to a bug in OpenSSL arm64 images aren't being built for Debian 11/Ubuntu 20.04, but:
 - It appears the bug is now fixed.
 - It doesn't mention Debian 12/Ubuntu 22.04 at all...

**Comment by eljog** [comment]
The devcontainer images are published in mcr registry.
Could you please share a link to the page that you are seeing with broken links?

**Comment by Clockwork-Muse** [comment]
The link is: https://hub.docker.com/_/microsoft-devcontainers?tab=description

**Comment by Clockwork-Muse** [comment]
Note that a number of projects that actually publish to the MCR/MAR still at least publish (or attempt to publish?) the list of tags and link to that page.  Eg, the [`dotnet-docker`](https://github.com/dotnet/dotnet-docker) repo.

**Comment by samruddhikhandale** [comment]
Thanks @Clockwork-Muse for bringing this to our attention, we'll shortly look into fixing it.

**Comment by eljog** [comment]
Thank you for reporting. I acknowledge that the information in t dockerhub is outdated. We will look into getting that updated as soon as possible.

**Comment by gauravsaini04** [comment]
#### Have pushed my code for this in [PR #47400](https://github.com/microsoft/mcrdocs/pull/47400)

**Comment by gauravsaini04** [comment]
PR merged.

**Comment by samruddhikhandale** [comment]
Closing as fixed, thanks @gauravsaini04
