### ISSUE TITLE
go update 1.21.6 from 2024-01-09 missing

### ISSUE THREAD

**Issue by DavidS-ovm** [devcontainers/images#921]
the latest builds of mcr.microsoft.com/devcontainers/go:dev-1.21-bookworm still contain go 1.21.5, missing the updates from [go1.21.6](https://go.dev/doc/devel/release#go1.21.minor)

please ensure that minor versions get updated timely, as this makes devcontainers lag behind other automated updates like dependabot or renovate, breaking workspaces with 

```
packages.Load error: err: exit status 1: stderr: go: go.work requires go >= 1.21.6 (running go 1.21.5)
```

For anyone else in the same situation, setting `GOTOOLCHAIN` to the required go version, or `auto` (see https://go.dev/doc/toolchain) downloads the required toolchain separately.

**Comment by eljog** [comment]
The latest `go` [image](https://mcr.microsoft.com/en-us/product/devcontainers/go/tags) released on 1/10 includes `go version go1.21.6 linux/amd64`

We push the new image to `latest` tag every month and sooner if there are major changes before that. If you would like to be on the bleeding edge of the image updates you may use the `dev` tag (example: `mcr.microsoft.com/devcontainers/go:dev-1`) of the images that we publish on a weekly or sooner cadence.
