### ISSUE TITLE
Support cuda-pytorch with miniconda

### ISSUE THREAD

**Issue by theo-barfoot** [devcontainers/images#933]
I have been using GPU compute and CUDA enabled devcontainers with miniconda and pytorch. I have found these particularly useful for machine learning development.

I have a template working and have tried it with a few CUDA and pytorch combinations.

Hopefully this will be useful to the wider community, so I will follow the steps for contribution:

- [ ] Open a PR 
- [ ] Create a release
- [ ] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [ ] Update https://github.com/devcontainers/images/issues/90
- [ ] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for all the insights, we appreciate it! 

Clarifying question, are you looking forward to update the existing [miniconda image](https://github.com/devcontainers/images/tree/main/src/miniconda) or contribute a new image/[Template](https://github.com/devcontainers/templates)?

Also, have you looked at [NVIDIA CUDA](https://github.com/devcontainers/features/tree/main/src/nvidia-cuda) which helps with simpler NVIDIA CUDA installation?

**Comment by theo-barfoot** [comment]
Hey! 

The idea was to contribute a new image and template. 

I didn't know about the NVidia CUDA feature, this seems to already implement the CUDA support I was looking to achieve, I will have an experiment using this feature.

However, if it could still be of value my Dockerfile is quite simple and basically just uses:

```
FROM nvidia/cuda:${CUDA_VERSION}-runtime-ubuntu22.04 as cuda-base
FROM continuumio/miniconda3 as miniconda-stage
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
COPY --from=cuda-base /usr/local/cuda /usr/local/cuda
COPY --from=miniconda-stage /opt/conda /opt/conda
RUN conda install pytorch=${PYTORCH_VERSION} pytorch-cuda=${CUDATOOLKIT_VERSION} -c pytorch -c nvidia
```

**Comment by samruddhikhandale** [comment]
> The idea was to contribute a new image and template.

We appreciate your Image and Template contribution, however, the `devcontainers/images` repo only accepts improvements and bug fixes for the [current set of maintained images](https://github.com/devcontainers/images/blob/main/src). It's the same with the `devcontainers/templates` repository.

However, we would appreciate if you could add this image or Template in a separate repository of your control. The [devcontainers/template-starter](https://github.com/devcontainers/template-starter) repo has more guidance on self authoring Templates.

Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/template-starter#adding-templates-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too!
