### ISSUE TITLE
Go 1.20 EOL scheduled for Feb 2024

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#944]
- [ ] Open a PR (Reference: https://github.com/devcontainers/images/pull/701)

**Comment by gauravsaini04** [comment]
> [!NOTE]
> Raised [PR #966](https://github.com/devcontainers/images/pull/966)

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/images/pull/966
