### ISSUE TITLE
Documentation of publishing custom images

### ISSUE THREAD

**Issue by hellodword** [devcontainers/images#968]
Found a related article: http://web.archive.org/web/20240217044438/https://blog.ianpreston.ca/posts/2022-12-30-devcontainers.html

And a `devcontainer build` script of cli: https://github.com/devcontainers/cli/blob/2a6ab1ac82f4917654205e2a9b1ac928260d902e/example-usage/image-build/build-image.sh

But for me it's confusing.

For example I have a `devcontainer.json` now:

```json
{
    "image": "mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04",
    "features": {
        "ghcr.io/devcontainers/features/node:1": {}
    },
    "postCreateCommand": "npm install -g @devcontainers/cli",
    "customizations": {
        "vscode": {
            "extensions": [
                "mads-hartmann.bash-ide-vscode"
            ]
        }
    }
}
```

VSCode will:
1. pull `mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04` 
2. run scripts from the `ghcr.io/devcontainers/features/node:1`
3. run `"postCreateCommand": "npm install -g @devcontainers/cli",`
4. install the extensions.

I want to publish that `devcontainer.json` and simply use the image in a new project:

```json
{
    "image": "ghcr.io/<owner>/<repo>/<name>:1.2.3",
    "postCreateCommand": "pwd"
}
```

I wish VSCode will:
1. pull `ghcr.io/<owner>/<repo>/<name>:1.2.3`
2. run `"postCreateCommand": "npm install -g @devcontainers/cli",`
3. run `"postCreateCommand": "pwd"`
4. install the extensions.

How could I do this in an easiest way currently?

**Comment by bamurtaugh** [comment]
Hi there, thanks for opening.

> I want to publish that devcontainer.json and simply use the image in a new project

I think this guide on prebuilding images would help: https://containers.dev/guide/prebuild#how-to. Is this similar to what you had in mind?
