### ISSUE TITLE
typescript-node npm scripts error access

### ISSUE THREAD

**Issue by DevinsonAlvarez** [devcontainers/images#969]
Hi, I'm trying build a `typescript-node` container but when I using **npm install** or **npm run dev** throws the next errors:

```sh
$ npm install
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /workspaces/react-app/node_modules/@esbuild/aix-ppc64
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/workspaces/react-app/node_modules/@esbuild/aix-ppc64'
npm ERR!  [Error: EACCES: permission denied, mkdir '/workspaces/react-app/node_modules/@esbuild/aix-ppc64'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/workspaces/react-app/node_modules/@esbuild/aix-ppc64'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

```sh
$ npm run dev

> react-app@0.0.0 dev
> vite

failed to load config from /workspaces/react-app/vite.config.ts
error when starting dev server:
Error: EACCES: permission denied, open '/workspaces/react-app/vite.config.ts.timestamp-1708117025459-8405b36e7d40a.mjs'
```

This error solves when I run as root using `sudo npm install/run dev` but I thing it is not the best idea to always run these commands as root. This is my **.devcontainer** file:

```json
{
  "name": "React App",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",

  "forwardPorts": [5173],

  "runArgs": ["--name", "react-app-devcontainer"],

  "postCreateCommand": "npm install",

  "customizations": {
    "vscode": {
      "extensions": [
        "dsznajder.es7-react-js-snippets",
        "esbenp.prettier-vscode",
        "dbaeumer.vscode-eslint",
        "ms-vscode.vscode-typescript-next"
      ]
    }
  }
}
```

**Comment by samruddhikhandale** [comment]
Hello 👋 

To me it looks like the `npm install` is run by `root` and hence, when within the dev container (with user:node), it won't allow `npm install` with a non-root user. However, I wasn't able to reproduce the issue with the dev config you provided. Am I missing something? 

![Image](https://github.com/devcontainers/images/assets/24955913/48e5a557-1ff7-40b8-a385-a5e072fdad55)

**Comment by DevinsonAlvarez** [comment]
> Hello 👋
> 
> To me it looks like the `npm install` is run by `root` and hence, when within the dev container (with user:node), it won't allow `npm install` with a non-root user. However, I wasn't able to reproduce the issue with the dev config you provided. Am I missing something?
> 
> ![Image](https://private-user-images.githubusercontent.com/24955913/306819016-48e5a557-1ff7-40b8-a385-a5e072fdad55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjY4OTIsIm5iZiI6MTcwODU2NjU5MiwicGF0aCI6Ii8yNDk1NTkxMy8zMDY4MTkwMTYtNDhlNWE1NTctMWZmNy00MGI4LWEzODUtYTVlMDcyZmRhZDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAxNDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZmJkMjA1MjJhNDQ2MjBiNTExODIzYjdkNTk2OWRlM2RjM2NlYTcxMGI2ZmE5NjQxMGZmYjAyYzA4NzI2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.srVT7Ecld4ct2_jsFnp6_hr90PuPWqBEWWMRikkHTO4)

The error happened because I build the contrainer from WSL and the permissions were not assigned to the **node** user, I solved it by changing the owner on folder using ´sudo chown -R $USER . && npm install´. This problem only happened while using WSL.
