### ISSUE TITLE
Please say if you can't simply find or patch boot.img or why it won't work...

### ISSUE THREAD

**Issue by TimmyTurner001** [devcontainers/images#978]
Please say if you can't simply find or patch boot.img or why it won't work...

Where are instructions to patch fdl2-sign.bin?

_Originally posted by @pndwal in https://github.com/topjohnwu/Magisk/issues/7866#issuecomment-1968515674_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
