### ISSUE TITLE
Ruby 3.0 EOL scheduled for 31st March 2024

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#998]
https://www.ruby-lang.org/en/downloads/branches/

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [x] Open a PR 
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

**Comment by bamurtaugh** [comment]
@samruddhikhandale sharing https://github.com/devcontainers/images/issues/1005 in case it ends up related to this work at all!

**Comment by gauravsaini04** [comment]
Updated PR [#1026](https://github.com/devcontainers/images/pull/1026)

**Comment by gauravsaini04** [comment]
pr merged to codebase

**Comment by gauravsaini04** [comment]
Please take a look at mcr updation pr #[47433](https://github.com/microsoft/mcrdocs/pull/47433)

**Comment by samruddhikhandale** [comment]
Closing as completed 🎉
